<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Longitude_txtlongitude</name>
   <tag></tag>
   <elementGuidId>91e07084-a686-4ff4-9717-54f54c320de8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtlongitude</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtlongitude']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be878db3-1ebc-48e4-9f52-1d4f11202181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0c72fdfa-6730-4ca0-92a4-5e34dda35939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\[[+-]?[0-9]*\.?[0-9]+,[+-]?[0-9]*\.?[0-9]+]</value>
      <webElementGuid>61c5ce14-d0a7-4c30-b9a3-c213bbfdf223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtlongitude</value>
      <webElementGuid>e867f92f-b2c1-4ba1-9e45-c0b7f9798bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b1dd1026-3bdd-4156-b9c2-c4376c3324d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtlongitude</value>
      <webElementGuid>2a671515-9e0a-47b9-a8b5-60e43809bbb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan longitude</value>
      <webElementGuid>d8c4a908-f2cb-4cfe-aa82-8565061a0a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>106.814095</value>
      <webElementGuid>c412309c-60c1-4c4a-89bc-049a670c423a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return((47&lt;event.keyCode &amp;&amp; event.keyCode&lt;58 &amp;&amp; event.shiftKey==false) || (event.keyCode==190 &amp;&amp; event.shiftKey==false) || event.keyCode==37 || event.keyCode==39 || event.keyCode==46 || event.keyCode==8)</value>
      <webElementGuid>349cb5e8-8f09-4f9d-ac9c-b4da79cb7c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtlongitude&quot;)</value>
      <webElementGuid>2d869b51-cf30-4b53-9ea5-04bed8c6fdf7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtlongitude']</value>
      <webElementGuid>fce85c59-100e-4553-933a-4bd2850aff82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmToko']/div[9]/div/div/input</value>
      <webElementGuid>f6eb6579-91a5-4a6b-843b-9c60f8d20d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/input</value>
      <webElementGuid>d60d2ba6-0b56-4891-bf6e-789bf7e51077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtlongitude' and @name = 'txtlongitude' and @placeholder = 'Masukkan longitude']</value>
      <webElementGuid>d4f26b59-7ee4-4193-b55e-65fb45ff633f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
