<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Toko_txtNamaToko</name>
   <tag></tag>
   <elementGuidId>b453d2a2-83c0-41fd-a591-09eb9590ce31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtNamaToko</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtNamaToko']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>192f2954-3dac-4035-be74-ab38128b3c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4ca6d516-dd35-4506-9591-770b37995822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNamaToko</value>
      <webElementGuid>bf5de15d-1f60-401b-ad83-2560be5e2071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2b7f3774-978c-4cf6-aadc-7bc43607f0de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input store name</value>
      <webElementGuid>7b9977d5-d289-40de-985f-a2fc35700d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtNamaToko</value>
      <webElementGuid>0f924c23-2746-412f-b25f-28fa591e0c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Transmart Cilandak</value>
      <webElementGuid>60a686af-3baa-4b4b-8406-eadd4ebbbd6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtNamaToko&quot;)</value>
      <webElementGuid>cc78e33f-ce65-4555-a707-e2d9cc88eb84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtNamaToko']</value>
      <webElementGuid>e80934ec-08b4-4c4e-a932-b6584ad250cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmToko']/div[3]/div/div/input</value>
      <webElementGuid>d7e91c31-55aa-49bc-99f2-817d728da3f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0df1fe18-c03a-4804-b1a2-30cde3d015ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtNamaToko' and @placeholder = 'Input store name' and @name = 'txtNamaToko']</value>
      <webElementGuid>405465b8-4c13-4e30-82e8-daed7d52b361</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
