<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telephone_txtTelepon</name>
   <tag></tag>
   <elementGuidId>fae2b2c7-656d-49d0-b300-9f73c11f44b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtTelepon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtTelepon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>736627b5-1066-4700-b6eb-149186968feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f0f11ffb-060b-4cb3-84cb-0964d1af4097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>c9a45005-430f-49f8-bc4b-9fa9ff1767d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtTelepon</value>
      <webElementGuid>22693bea-1c47-4ae9-a247-6837cc049dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input telephone number</value>
      <webElementGuid>919331cf-c4d2-44bc-b5e0-2defadb50f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>numberOnly(this.id);</value>
      <webElementGuid>843284a6-e56c-43f5-b562-1f0c3db920f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8a212680-651a-4eeb-9890-d813f9d8ef6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtTelepon</value>
      <webElementGuid>6962bcb5-809e-489c-af51-fbdd731e65da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>123456789</value>
      <webElementGuid>d0daaaf4-8fd0-40bf-9d2b-63a3aa85d0d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtTelepon&quot;)</value>
      <webElementGuid>b02d9eed-f052-4606-949a-72511fbbc71e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtTelepon']</value>
      <webElementGuid>3615fda3-a8be-405c-9070-30ddfe0f6497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmToko']/div[7]/div/div/input</value>
      <webElementGuid>fa5d3bb7-e137-4f2d-968f-aaa480811cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>5ec688b2-88d0-45fa-a53f-75ddb0f7fcf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtTelepon' and @placeholder = 'Input telephone number' and @name = 'txtTelepon']</value>
      <webElementGuid>edde2413-dfcd-43d0-94ec-0d7c67159d8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
