<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telephone_txtTelepon</name>
   <tag></tag>
   <elementGuidId>6fcf9bed-2f73-48bb-9e58-70c35eb83ec0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtTelepon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtTelepon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75e0a780-d38a-4b43-ac75-9346bd69e323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3e262a83-f70c-45c9-8d1a-a71acd223f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>a634999e-f1c4-4f2a-be29-ecb6d9bfc710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtTelepon</value>
      <webElementGuid>e7fb9e79-f2ba-482b-95ac-4fbd9faa811e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input telephone number</value>
      <webElementGuid>80a44cbf-431f-46fb-be79-db150f10e410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>numberOnly(this.id);</value>
      <webElementGuid>85113f86-4104-43ca-95f5-2fdeac9f337a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0dfb3bc4-4612-431b-bb59-9fdd020cd4ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtTelepon</value>
      <webElementGuid>78de2fab-1735-41f8-ade6-3ce2830400ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtTelepon&quot;)</value>
      <webElementGuid>4ead438d-4c6c-43fd-a4f8-c62a322e972f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtTelepon']</value>
      <webElementGuid>cf5b4be2-4581-42bb-bb19-214852f369fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmToko']/div[7]/div/div/input</value>
      <webElementGuid>0b896846-6f8e-4fe7-9289-4538feb7a75a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>783e99c0-aa22-4016-b85f-f661f8cfca07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtTelepon' and @placeholder = 'Input telephone number' and @name = 'txtTelepon']</value>
      <webElementGuid>55e9ef64-0d67-4531-89d6-61a58901318f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
