<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Printer_category</name>
   <tag></tag>
   <elementGuidId>ba621069-0bae-4d59-bfc9-7bfde38f7530</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#category6462074d1f3b15c5340b1dc2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='category62ff40b0e4b6a329fa76acc5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6c83383-aa56-4ca9-8adf-262e40d99ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d732cc97-8125-4214-95da-a7ed9ed30df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category</value>
      <webElementGuid>5cc63550-223f-43c8-9091-93847c00068e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>dec26e92-5f1f-42e0-a993-11fcda5affba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category6462074d1f3b15c5340b1dc2</value>
      <webElementGuid>106c6ec4-4e1e-4a01-8bc8-5b2c64e17aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>6462074d1f3b15c5340b1dc2</value>
      <webElementGuid>b2a61dbe-fdc5-43c8-82cb-5c7a29930ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category6462074d1f3b15c5340b1dc2&quot;)</value>
      <webElementGuid>43b9596c-3a35-4435-b719-d99b56b75dd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='category6462074d1f3b15c5340b1dc2']</value>
      <webElementGuid>832d13b4-bcaf-4fc1-938a-50602f433043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comboBoxCategory']/div[8]/input</value>
      <webElementGuid>f778076a-dc7c-45d3-b770-9322a875976a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>5f7eef02-03f4-4678-8144-187bae42cc75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'category' and @id = 'category6462074d1f3b15c5340b1dc2']</value>
      <webElementGuid>9b839100-9ba1-4772-a044-61a710350596</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
