<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TV_category</name>
   <tag></tag>
   <elementGuidId>26283cca-e097-4f6e-a50b-122f5e7a62c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#category62f3169e2b878f0347211ea0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='category62f316952b878f0347211e9f']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd2ecbd6-48a4-41fc-a57c-51e91d7f18b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2f20560e-aef2-4582-b555-090e0aea9271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category</value>
      <webElementGuid>c79eb80e-67f5-40ae-bfb5-4886c649b023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>57b8ea6b-0394-4a63-afb0-bb32f9176755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category62f3169e2b878f0347211ea0</value>
      <webElementGuid>b6f8a286-8077-409d-95bc-84999c67c26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>62f3169e2b878f0347211ea0</value>
      <webElementGuid>2b0efc86-431d-4d02-8a65-6b709f3a89c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category62f3169e2b878f0347211ea0&quot;)</value>
      <webElementGuid>b4daab19-85af-42d1-af38-ba9076747f29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='category62f3169e2b878f0347211ea0']</value>
      <webElementGuid>0a5013ac-7844-45a4-a9b6-042763b8e225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comboBoxCategory']/div[3]/input</value>
      <webElementGuid>355bb6f7-b2f2-4ad3-9053-1f856262b9b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>60646d18-8b0d-49a2-bf89-b53b41946b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'category' and @id = 'category62f3169e2b878f0347211ea0']</value>
      <webElementGuid>7163e082-a9c1-4b0b-867c-a31c09751cbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
