<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kamera  Recoder_category</name>
   <tag></tag>
   <elementGuidId>fdde52e7-2fe1-4952-9ac9-178d2cfa90e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#category62f9d04a9ae061df04377ef6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='category62f316ad2b878f0347211ea1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29413be8-4fd1-4226-bb97-11a5b10ba09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4a468f5d-4500-4109-a2ed-7e2b56afd690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category</value>
      <webElementGuid>058eb90b-c39c-492d-9695-0daae7323555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>05cb09cc-d463-4988-8fa6-ca0e9247feea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category62f9d04a9ae061df04377ef6</value>
      <webElementGuid>9ff79a49-d40e-437c-90bc-82d28c6f15d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>62f9d04a9ae061df04377ef6</value>
      <webElementGuid>5a2bc431-7c30-420f-a382-15ced26eca00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category62f9d04a9ae061df04377ef6&quot;)</value>
      <webElementGuid>b71046bf-8ed3-4eb1-9756-1fb593c23b46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='category62f9d04a9ae061df04377ef6']</value>
      <webElementGuid>ecda68f4-21e1-46ed-91d3-753f9f4122f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comboBoxCategory']/div[5]/input</value>
      <webElementGuid>974ab99b-d9bc-4a91-8a5d-3c1faa214222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>e90f23fa-4da0-473c-b058-b33a90183319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'category' and @id = 'category62f9d04a9ae061df04377ef6']</value>
      <webElementGuid>3bef81b4-3735-4aba-ad46-bdb942a57e88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
