<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Author</name>
   <tag></tag>
   <elementGuidId>fd18d0fc-e964-43f0-b6d2-fbddbfafef44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > th</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='complex-header-datatable']/div/div[2]/div/div[2]/table/tbody/tr[2]/th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>11086e3e-95ec-419e-93da-6c6790c133bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Author</value>
      <webElementGuid>04c52039-5e31-4f22-9b82-3099fd65d2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;complex-header-datatable&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-4&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body border-bottom p-1&quot;]/table[1]/tbody[1]/tr[2]/th[1]</value>
      <webElementGuid>6d58a7ad-141a-4df9-8702-294474ed2699</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='complex-header-datatable']/div/div[2]/div/div[2]/table/tbody/tr[2]/th</value>
      <webElementGuid>5460c7df-5373-41af-a805-0b0cfff36ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Release Date'])[1]/following::th[1]</value>
      <webElementGuid>8a761f72-84f9-4283-950b-2e9397bd498e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail FAQs'])[1]/following::th[2]</value>
      <webElementGuid>09bf2457-26b0-4e57-8813-41a0cb53296d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eva'])[2]/preceding::th[1]</value>
      <webElementGuid>534fd011-2841-42a9-8a01-92fae0224900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Views'])[1]/preceding::th[1]</value>
      <webElementGuid>888baeba-4b6e-4ad3-8b85-f038f4ae4e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Author']/parent::*</value>
      <webElementGuid>a28cc8fb-9fe7-4b45-bb9e-949d3f0fc835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/th</value>
      <webElementGuid>362cbdb0-fd57-4263-ab5d-860697ad1e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Author' or . = 'Author')]</value>
      <webElementGuid>d98ca383-2e32-427d-aac4-40ffbc09442c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
