<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Komputer  Laptop_category</name>
   <tag></tag>
   <elementGuidId>c0ea12e8-326e-4ca8-99be-537d58c9a03a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='category62f316842b878f0347211e9e']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#category62f316952b878f0347211e9f</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37a6ed00-a9bc-426f-9a09-127eb3ba4ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>02e4809e-7a59-44f1-a239-6a028ac46cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category</value>
      <webElementGuid>e9bdde48-7b56-4f9e-b9bd-7c031d485a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>8e722da1-b31d-413b-9fb9-dbd952565a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category62f316952b878f0347211e9f</value>
      <webElementGuid>ce205959-eb47-4fce-87e9-425ee7ce7c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>62f316952b878f0347211e9f</value>
      <webElementGuid>5718471b-3ea9-4b06-b0f9-206676fce670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category62f316952b878f0347211e9f&quot;)</value>
      <webElementGuid>bc52dadd-e8cd-41dd-a193-63f25643c0ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='category62f316952b878f0347211e9f']</value>
      <webElementGuid>a81974c7-d93f-42ff-b1da-d8326d50f1ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comboBoxCategory']/div[2]/input</value>
      <webElementGuid>d145b244-dd6c-43f3-bfa0-db9cb76cb765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>9edcadac-bd23-4e94-a15d-f43fca2e751d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'category' and @id = 'category62f316952b878f0347211e9f']</value>
      <webElementGuid>40ddccaf-0c2d-47e7-9350-1c78c3ad1a9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
