<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TV_category</name>
   <tag></tag>
   <elementGuidId>391a807d-7fa2-439b-9abd-6c494cc2d584</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='category62f316952b878f0347211e9f']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#category62f3169e2b878f0347211ea0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>decdf34b-793c-4478-9a12-0aac6342af18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>978f3384-50dd-4f26-b3bf-03243b607dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category</value>
      <webElementGuid>cd2ca471-7ff8-467c-bcb2-fa2a2f91c4ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>c7f99ab1-12c3-4e6c-8477-b9fb8c4ce752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category62f3169e2b878f0347211ea0</value>
      <webElementGuid>68ca1cca-37a6-4233-80a8-82c7ff108fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>62f3169e2b878f0347211ea0</value>
      <webElementGuid>245a4c44-c460-44fc-97cd-bb608702c459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category62f3169e2b878f0347211ea0&quot;)</value>
      <webElementGuid>1102b40c-1033-4607-9129-54872ed6c915</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='category62f3169e2b878f0347211ea0']</value>
      <webElementGuid>a9ad4f70-bf56-449a-9835-7a96803b9220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comboBoxCategory']/div[3]/input</value>
      <webElementGuid>2d8a8c4c-b7c1-41c8-952b-a4b915a233bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>5d105344-87ef-4b5f-9b85-708f442a97b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'category' and @id = 'category62f3169e2b878f0347211ea0']</value>
      <webElementGuid>3b59d8f1-6ab0-4e43-ba0c-8b638de29bdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
