<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Audio_category</name>
   <tag></tag>
   <elementGuidId>e065d829-e770-43a0-a8d4-084527370d23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='category62ff4089e4b6a329fa76acc4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#category62ff40b0e4b6a329fa76acc5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3cf5621a-5c13-401e-9653-eab0765702c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>29c4279c-4043-40d7-b22e-19fdf1a0b16f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category</value>
      <webElementGuid>a1008da9-bbb5-4ba6-9908-2c59478b4417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>60910e00-1fa9-45ad-a577-5d3daf41af51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category62ff40b0e4b6a329fa76acc5</value>
      <webElementGuid>a30cc032-8234-4945-8f98-da9377de53bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>62ff40b0e4b6a329fa76acc5</value>
      <webElementGuid>f3559fbc-6f9d-4287-a6d0-e25aac15e5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category62ff40b0e4b6a329fa76acc5&quot;)</value>
      <webElementGuid>3fe93f7b-3041-45aa-b1cf-5db0c29363f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='category62ff40b0e4b6a329fa76acc5']</value>
      <webElementGuid>33d79769-d104-498f-9e6b-ba0cb01f80dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comboBoxCategory']/div[7]/input</value>
      <webElementGuid>fb53fd7c-4b13-462d-800e-95e6f2eff6de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>730819f8-0d59-43e8-ad29-b5f3c350372e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'category' and @id = 'category62ff40b0e4b6a329fa76acc5']</value>
      <webElementGuid>fca62bfb-6619-424c-bdcc-8b15c46612bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
