<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Detail_1_2</name>
   <tag></tag>
   <elementGuidId>ea510db1-6e8e-4c84-b4af-fab4dccf9456</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tbl-user-management']/tbody/tr[4]/td[8]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d32544eb-92a9-48ef-9b01-8cef7afe5b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat-dashboard.blicicil.com/user-management/detail?token=6425315a8d104513cc7eb195</value>
      <webElementGuid>6c6b71af-7b9d-4b41-8fbe-21a8b3980559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-flat-info</value>
      <webElementGuid>0b197e0e-97e3-4ef8-9254-89bbaba606e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>89c0f13e-50e7-4be1-b1b1-d915f12b872d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl-user-management&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[8]/a[@class=&quot;btn btn-flat-info&quot;]</value>
      <webElementGuid>a83a6df5-8f08-4a98-b07b-b08a754a88c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbl-user-management']/tbody/tr[4]/td[8]/a</value>
      <webElementGuid>e1519510-f4f4-436c-a7f2-c927f7343173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Detail')])[4]</value>
      <webElementGuid>6db6905c-0bfd-450d-953a-c75c74156f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[2]/following::a[1]</value>
      <webElementGuid>111f73c5-dbfb-4e54-84f7-53b029f0b35e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 20.000.000'])[3]/following::a[1]</value>
      <webElementGuid>2af3eb95-755f-46cc-9a29-6d8c0b424782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Renaka agusta'])[1]/preceding::a[1]</value>
      <webElementGuid>5f459d74-b961-4f76-9d0d-3b416d7ed173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 0'])[5]/preceding::a[1]</value>
      <webElementGuid>3755cda1-e1a4-4ffa-b48a-b8c23a933426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://uat-dashboard.blicicil.com/user-management/detail?token=6425315a8d104513cc7eb195')]</value>
      <webElementGuid>0105aa3d-2fb1-4ba5-b578-8b5312de36f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[8]/a</value>
      <webElementGuid>496ca94a-d997-461d-9cc0-0ca83c78bdd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat-dashboard.blicicil.com/user-management/detail?token=6425315a8d104513cc7eb195' and (text() = 'Detail' or . = 'Detail')]</value>
      <webElementGuid>d043952f-d014-4c1a-a501-65e84eb38d38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
