<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PENDING</name>
   <tag></tag>
   <elementGuidId>a0973b25-2751-4d4a-bceb-7ef899da93aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#status_pengajuan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='status_pengajuan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6674f121-65f6-4f92-8156-0f6bc1c680ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>status_pengajuan</value>
      <webElementGuid>e9662b16-012b-4ecb-950b-72c8dae07e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-pill p-status text-white mb-1 bg-warning</value>
      <webElementGuid>d5fcb722-c20d-4fe0-b62c-df7a9a37e475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PENDING</value>
      <webElementGuid>ec1221f3-54c0-43ab-857e-88ad4c26f5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;status_pengajuan&quot;)</value>
      <webElementGuid>73084b91-51d3-4a51-8c62-0f8133c8b1c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='status_pengajuan']</value>
      <webElementGuid>aeac2dfe-2113-4c33-b126-4d54ac63581e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='felix audrey'])[1]/following::div[1]</value>
      <webElementGuid>fdf25732-e734-45d8-ada2-8df60bb2e8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Profile'])[2]/following::div[7]</value>
      <webElementGuid>a0df05a8-dfe2-446e-8768-6546f71314c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::div[2]</value>
      <webElementGuid>b85c8231-41f4-44ec-8964-4e2aee29235e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Limit maks:'])[1]/preceding::div[5]</value>
      <webElementGuid>ce2b8f99-224e-4ac4-8b55-a6f8d391ee52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PENDING']/parent::*</value>
      <webElementGuid>304a12d3-6e8a-4ef2-b15f-9aa608166631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>4fa730ed-d975-4d87-bf2a-a1fd3343fae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'status_pengajuan' and (text() = 'PENDING' or . = 'PENDING')]</value>
      <webElementGuid>b2fecc65-6279-4d0d-86e1-a672f5541b42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
