<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_REJECT</name>
   <tag></tag>
   <elementGuidId>7f80dad7-73ee-454a-a7cb-de7830de69c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#status_pengajuan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='status_pengajuan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>adbdcab3-db41-45d8-9c4f-6988d0a7f6a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>status_pengajuan</value>
      <webElementGuid>bbb8a546-b3c3-4be0-a0e8-b45512e13332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-pill p-status text-white mb-1 bg-danger</value>
      <webElementGuid>50468468-1a1e-4827-bb63-41b6e086b65d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>REJECT</value>
      <webElementGuid>f526594d-aede-43f2-accb-b3e33a5a092d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;status_pengajuan&quot;)</value>
      <webElementGuid>29fe3a0c-bfd4-4517-b96b-0d0e9ea2b471</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='status_pengajuan']</value>
      <webElementGuid>2759535d-9afe-4cca-9086-c4465abde34a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MARLINA FAUZI MIRRA'])[1]/following::div[1]</value>
      <webElementGuid>2d42ac76-9028-4caf-b823-4f29ed7a5bf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Profile'])[2]/following::div[7]</value>
      <webElementGuid>0982f8c3-30dd-4e44-ab60-4a3ea4b925fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::div[2]</value>
      <webElementGuid>705c8431-c87a-4b22-92ea-54d2fcf93aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Limit maks:'])[1]/preceding::div[5]</value>
      <webElementGuid>961d015a-2721-4a10-9bd9-079340c6d371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='REJECT']/parent::*</value>
      <webElementGuid>2bdbb8c2-02e7-4361-add0-6c83c7704445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>5e979f35-a2ae-4c48-91b8-fdf8568dddd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'status_pengajuan' and (text() = 'REJECT' or . = 'REJECT')]</value>
      <webElementGuid>03027f82-0443-4390-b333-6ab6f344ac82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
