<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_List Motorcycle Transaction BliCicil _ec3f45</name>
   <tag></tag>
   <elementGuidId>fb5c86c0-1986-4c0c-87c0-a3fc7d620401</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filterSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filterSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d35c9fe-b58c-4bd8-886c-7e05f47469e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>76741817-9bd4-41b6-ae37-3a0771d821b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filterSearch</value>
      <webElementGuid>b07f90c5-240d-443c-80b5-1374641ad61a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e119bc99-112c-4b6f-b590-71c1951b8abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan keyword</value>
      <webElementGuid>78f339e4-9ace-4a61-b395-d521ffcdb0d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filterSearch</value>
      <webElementGuid>a3401012-74dd-4b46-be32-46ebddae9755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterSearch&quot;)</value>
      <webElementGuid>9fb8d219-f352-4679-a95b-24a110039e5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filterSearch']</value>
      <webElementGuid>0e8a1f94-89dd-4c13-90db-c5f4ad5f5504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='complex-header-datatable']/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>627ee007-bf87-4905-ab8e-c482b86b97f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>dcbe5c62-afe0-4dac-b16e-b0c272b0d493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'filterSearch' and @placeholder = 'Masukkan keyword' and @name = 'filterSearch']</value>
      <webElementGuid>aad9dcf4-d3e2-4301-9d78-0f86144c971f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
