<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Detail</name>
   <tag></tag>
   <elementGuidId>03a76f41-6e93-4276-acd3-89c44090248f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tbl-user-management']/tbody/tr/td[8]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-flat-info</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>41fe1c91-f8a4-44c7-ab96-17270857bddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat-dashboard.blicicil.com/user-management/detail?token=63c900953ff52505dc7c9eee</value>
      <webElementGuid>81fcd4c5-1c5c-4757-a7f4-21e3faa76b7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-flat-info</value>
      <webElementGuid>6ea0baa7-8b72-4f34-9a7f-58c12346c20a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>511388e2-0a4b-4682-91d9-1fbaa4f071b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl-user-management&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[8]/a[@class=&quot;btn btn-flat-info&quot;]</value>
      <webElementGuid>dc49eaae-6466-4fbd-bb38-1aa488900e9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbl-user-management']/tbody/tr/td[8]/a</value>
      <webElementGuid>7254edc3-2fe3-4c57-ad58-b9a44f7f015e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Detail')]</value>
      <webElementGuid>973fdb11-a757-4361-a724-e05e309ad6bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::a[1]</value>
      <webElementGuid>ac1180f8-82fe-4cdc-acac-c22bab84d44c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 0'])[2]/following::a[1]</value>
      <webElementGuid>994bfdef-5a23-43db-83cd-302490649916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nun'])[1]/preceding::a[1]</value>
      <webElementGuid>2a695ec0-4e95-4776-b9d5-c1e4f8c76388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::a[1]</value>
      <webElementGuid>a4b5246d-2e94-4794-9d0d-b397e6c39c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Detail']/parent::*</value>
      <webElementGuid>2fcac80b-eadf-49a0-96b3-4ceb7da5be03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://uat-dashboard.blicicil.com/user-management/detail?token=63c900953ff52505dc7c9eee')]</value>
      <webElementGuid>608ea889-3570-4227-b8ee-f8bd994e69b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/a</value>
      <webElementGuid>3cece3ad-fc6e-4f23-a4d5-e82acc55bbe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat-dashboard.blicicil.com/user-management/detail?token=63c900953ff52505dc7c9eee' and (text() = 'Detail' or . = 'Detail')]</value>
      <webElementGuid>adf907f3-9d62-4bb8-9964-96e8bf809d97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
