<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Foto Identitas</name>
   <tag></tag>
   <elementGuidId>840a3951-23ea-4964-b2c2-4322ad4772ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pills-photo-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pills-photo-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a09c0f98-db62-458e-92b2-00a2bc9ca46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link user-detail</value>
      <webElementGuid>1e1a8572-be58-4522-b23f-f9602e2114d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pills-photo-tab</value>
      <webElementGuid>af298e59-5ec6-4546-bc7a-372f844f5dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>pill</value>
      <webElementGuid>dcb5c0d5-07c3-46d2-bff9-6a98d0006ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#pills-photo</value>
      <webElementGuid>ebf9e279-16ac-4fbd-8182-6599d51708dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>4af168b5-771d-4adf-bc8f-49b097b302b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pills-photo</value>
      <webElementGuid>a4cdb216-fd7d-4cfa-8f2c-2049d3e81640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>351ca364-40dd-45db-8581-84b179c40bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Foto Identitas</value>
      <webElementGuid>ae9326d2-1cfc-4127-a5fc-1b229274ef71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pills-photo-tab&quot;)</value>
      <webElementGuid>8f25ceae-0985-4011-9230-1b76cfbafd98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pills-photo-tab']</value>
      <webElementGuid>1b47a135-15c8-4f84-be4c-d577921d42b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pills-tab']/li[5]/a</value>
      <webElementGuid>69f871ed-d8a3-4702-9e3e-264fee7d7795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Foto Identitas')]</value>
      <webElementGuid>799b56cb-8d09-4f41-8049-e84251c94602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Kontak'])[1]/following::a[1]</value>
      <webElementGuid>55ad67ca-0699-4ae2-ba56-d9d4ec2146af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Pekerjaan'])[1]/following::a[2]</value>
      <webElementGuid>1288e3a4-ce58-44bd-a2d7-be731918452d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=', All rights Reserved'])[1]/preceding::a[2]</value>
      <webElementGuid>1d7d449b-2c3e-48ff-8056-8becdf490708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Foto Identitas']/parent::*</value>
      <webElementGuid>498cb523-d187-4572-8a8f-a22cf4b488b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#pills-photo')]</value>
      <webElementGuid>6cf1704a-8c30-45df-a7a5-0e1cff3cf234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[5]/a</value>
      <webElementGuid>9f3be759-0560-4241-87d6-83cec7f2cffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pills-photo-tab' and @href = '#pills-photo' and (text() = 'Foto Identitas' or . = 'Foto Identitas')]</value>
      <webElementGuid>c39c6715-da1f-4e3b-a43e-ad09ea8ab3a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
