<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Informasi Nasabah</name>
   <tag></tag>
   <elementGuidId>d6d07532-dc5e-4f47-8f42-1d3084570249</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pills-nasabah-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pills-nasabah-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>40393d8a-5ca3-422b-ab50-c86bd8105e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link user-detail</value>
      <webElementGuid>78f472c6-87a5-4704-95c2-a6ae00feb1d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pills-nasabah-tab</value>
      <webElementGuid>b05d0e7f-d79e-491c-9246-60da32d6fb0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>pill</value>
      <webElementGuid>864782f5-f592-4bb9-8b5a-0216fb695939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#pills-nasabah</value>
      <webElementGuid>3b015006-5b8c-4351-919a-6e97dbd95e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>fce699fe-1290-4eef-8ee8-2660eb9a1015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pills-nasabah</value>
      <webElementGuid>916cb9b1-bf6c-4ff0-beaa-52942838caf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>246ee323-6665-4576-9ddc-9b3e84949daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Informasi Nasabah</value>
      <webElementGuid>ad2bb970-303b-4664-83dd-2c8f16566b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pills-nasabah-tab&quot;)</value>
      <webElementGuid>4d09b139-a780-42fd-9159-ab9ddc5c8af7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pills-nasabah-tab']</value>
      <webElementGuid>f0e98171-1737-4cf3-8e98-d6b7b9895feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pills-tab']/li/a</value>
      <webElementGuid>6cfd16bd-704d-4dd6-8cb8-8bb7f9a4b362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Informasi Nasabah')]</value>
      <webElementGuid>2f23b404-75c5-44b2-a49c-47932816be74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Pengajuan:'])[1]/following::a[1]</value>
      <webElementGuid>05a5668c-7fa3-43ca-811f-8d0932e3ebc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp100.000'])[1]/following::a[1]</value>
      <webElementGuid>55ab1f66-b38e-4805-ba80-43721a1d6c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Alamat'])[1]/preceding::a[1]</value>
      <webElementGuid>4c63e362-830b-4c17-a92e-40c03e161681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Pekerjaan'])[1]/preceding::a[2]</value>
      <webElementGuid>80674bd7-8973-4e7a-8558-9bbcd2df7123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Informasi Nasabah']/parent::*</value>
      <webElementGuid>4999946d-eff7-4d0d-980b-f51f606b4e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#pills-nasabah')]</value>
      <webElementGuid>4780f05c-fc71-40ee-bf65-634b67099a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a</value>
      <webElementGuid>46b392fb-8a3d-4c99-be25-32401cde274b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pills-nasabah-tab' and @href = '#pills-nasabah' and (text() = 'Informasi Nasabah' or . = 'Informasi Nasabah')]</value>
      <webElementGuid>d2f78610-a086-42e2-b2a8-e83c9935b750</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
