<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Informasi Kontak</name>
   <tag></tag>
   <elementGuidId>c59fb2b3-5db2-4b0e-958a-20cfa5f7d834</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pills-kontak-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pills-kontak-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>48a20adc-5801-4a86-b987-cafb17f5a1bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link user-detail</value>
      <webElementGuid>65c00f41-4e91-460a-8aa5-f785f60537bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pills-kontak-tab</value>
      <webElementGuid>fd4b44aa-8fcd-4f86-b750-f8a193d080d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>pill</value>
      <webElementGuid>c52d90f8-9df7-4c00-9cf0-ebced151f46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#pills-kontak</value>
      <webElementGuid>196714ad-106f-4af2-9ad6-f91f5578fa0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>5dfbdf16-9f93-4fdb-9498-a814e74e2d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pills-kontak</value>
      <webElementGuid>65edeacb-9c92-4e1c-a78c-cb02e6245b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ccab41c2-f395-421b-8e01-b5c3ea485b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Informasi Kontak</value>
      <webElementGuid>8090ea0a-944e-4e62-96c1-95af6f3c81c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pills-kontak-tab&quot;)</value>
      <webElementGuid>9806d046-93f0-4995-ac76-4c3a210a8492</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pills-kontak-tab']</value>
      <webElementGuid>1b4eb22a-3e82-4a7a-af6c-a2a4dec6d72d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pills-tab']/li[4]/a</value>
      <webElementGuid>72592a41-c966-42a8-9509-a80597b3d673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Informasi Kontak')]</value>
      <webElementGuid>8158b65d-d71c-4866-a52f-49f36f05a935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Pekerjaan'])[1]/following::a[1]</value>
      <webElementGuid>35a2df9b-e20d-46c2-9ca8-0968573c8f34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Alamat'])[1]/following::a[2]</value>
      <webElementGuid>0301579d-be4b-4e96-8211-420bdf9ee1e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Foto Identitas'])[1]/preceding::a[1]</value>
      <webElementGuid>7f34099b-78a7-4a13-851a-bca20a317b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Informasi Kontak']/parent::*</value>
      <webElementGuid>687d03c2-a935-433a-b12a-6e801a4ab44c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#pills-kontak')]</value>
      <webElementGuid>869cd76e-4696-412b-aac1-c4fc52eaa936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[4]/a</value>
      <webElementGuid>84c6b3f0-4447-4ff4-bd3f-d84895772683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pills-kontak-tab' and @href = '#pills-kontak' and (text() = 'Informasi Kontak' or . = 'Informasi Kontak')]</value>
      <webElementGuid>326959df-134d-4bb6-aa3a-3cc9e5fbd316</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
