<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PENDING</name>
   <tag></tag>
   <elementGuidId>aae57c6d-ac76-4e8a-8ac4-5d4d47e97edb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#status_pengajuan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='status_pengajuan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9bebea1e-fb4e-4c5c-81ac-99b084e57483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>status_pengajuan</value>
      <webElementGuid>c2d433a8-4afd-4829-b2cb-a0b1030395c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-pill p-status text-white mb-1 bg-warning</value>
      <webElementGuid>7c8d3eb9-5711-43d2-9701-98825df175c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PENDING</value>
      <webElementGuid>364e3a63-c832-4ca4-8c30-1bac5e1aae42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;status_pengajuan&quot;)</value>
      <webElementGuid>1a176c0e-cf56-493f-b29f-170e4b462831</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='status_pengajuan']</value>
      <webElementGuid>8b0aaf63-b1d8-4a1c-87bb-cf3260e4f182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='felix audrey'])[1]/following::div[1]</value>
      <webElementGuid>f655798a-31a2-412f-8b9f-91fe705eb0a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Profile'])[2]/following::div[7]</value>
      <webElementGuid>92ca3dab-78fd-4187-b008-37d7bfd40e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::div[2]</value>
      <webElementGuid>839c6d3b-be6c-4692-bf41-ca72a3e3277c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Limit maks:'])[1]/preceding::div[5]</value>
      <webElementGuid>de96e6f9-a6b0-4732-8170-7d81f116c158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PENDING']/parent::*</value>
      <webElementGuid>f3fd6ebb-2ead-428d-b2aa-5e3a426ed667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>122ca83e-9b09-4982-8000-e631e02fb87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'status_pengajuan' and (text() = 'PENDING' or . = 'PENDING')]</value>
      <webElementGuid>6e9fe9ce-5fb9-4226-9a55-1a8994434e1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
