<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_User Profile_photo_profile</name>
   <tag></tag>
   <elementGuidId>7cbeb7ce-4827-4c21-b93a-e87d589bc528</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#photo_profile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='photo_profile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>31258a55-3644-4450-bd8b-489a0b8c4c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>photo_profile</value>
      <webElementGuid>3db695fb-f81a-4202-8487-925d97cef86f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://blicicil.oss-ap-southeast-5.aliyuncs.com/stg/images/profile/63214ee364bd8a66633248a6/profile.png</value>
      <webElementGuid>49084441-2ae0-4f5a-a453-31af58ec065f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.onerror=null;this.src='https://uat-dashboard.blicicil.com/assets/images/default.png'</value>
      <webElementGuid>71c3bf26-c50f-45e1-a0d2-3d7dee83445d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;photo_profile&quot;)</value>
      <webElementGuid>ce6ba8a2-de9f-43cb-91c5-022d2366138a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='photo_profile']</value>
      <webElementGuid>0f7c8440-195d-45ae-a036-47eac89b36fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://blicicil.oss-ap-southeast-5.aliyuncs.com/stg/images/profile/63214ee364bd8a66633248a6/profile.png')]</value>
      <webElementGuid>eae4cd05-3f72-4bb7-b19f-a7d77b2983dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>71113a11-9973-4b9d-94d7-1818df01730c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'photo_profile' and @src = 'https://blicicil.oss-ap-southeast-5.aliyuncs.com/stg/images/profile/63214ee364bd8a66633248a6/profile.png']</value>
      <webElementGuid>b5b5fb93-a68e-4a6c-9c79-489300cf178d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
