<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_User Profile_photo_profile</name>
   <tag></tag>
   <elementGuidId>fcfbf7b4-275a-4101-bd49-541b2997a3ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#photo_profile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='photo_profile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>78fa4283-d39c-402f-a79a-07cb399e91ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>photo_profile</value>
      <webElementGuid>4a212ea7-696b-4325-9a5e-11d26f8212b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://uat-dashboard.blicicil.com/assets/images/default.png</value>
      <webElementGuid>a2fc06bb-177e-4b24-9bf3-3a2146fbb361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.onerror=null;this.src='https://uat-dashboard.blicicil.com/assets/images/default.png'</value>
      <webElementGuid>b092f4cf-3a80-4c23-852d-54ccfb83ef01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;photo_profile&quot;)</value>
      <webElementGuid>e1d9cd3f-d53b-4c61-a801-ae50257e01af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='photo_profile']</value>
      <webElementGuid>1d6e8358-d215-4f59-85c6-7b1812611dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://uat-dashboard.blicicil.com/assets/images/default.png')]</value>
      <webElementGuid>12fbcc3b-d65d-4055-9df5-bad5b3a6b2ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>4edf9333-1b14-441e-9941-59d93e0fb157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'photo_profile' and @src = 'https://uat-dashboard.blicicil.com/assets/images/default.png']</value>
      <webElementGuid>099cc417-5c1a-4476-8618-9d5c25b78d60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
