<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Toko_txtNamaToko</name>
   <tag></tag>
   <elementGuidId>e0b1d7b6-4c08-47dc-b3c4-34c76fde7d05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtNamaToko</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtNamaToko']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0addfc9b-5996-4814-82fc-b06e06ac4c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3a543071-50eb-4b62-ab83-67b01e6fb5bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNamaToko</value>
      <webElementGuid>9b2bda32-3f4f-43f8-bf1e-2a007f25170e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3a7619ac-44e0-4b3b-8bbd-efc36687f3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input store name</value>
      <webElementGuid>947d5049-d1c2-4fd7-9789-ec9b12141704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtNamaToko</value>
      <webElementGuid>c24bfc1d-cc29-4b3e-b6cb-a354152e4bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Transmart Cilandak</value>
      <webElementGuid>6101d0bb-8093-4f95-9e26-f40f4ab5d106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtNamaToko&quot;)</value>
      <webElementGuid>34a5527c-67c6-47e5-bca0-652d04b42088</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtNamaToko']</value>
      <webElementGuid>7d29e35e-5d1d-4bee-914a-378567e9f51d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmToko']/div[3]/div/div/input</value>
      <webElementGuid>b44e848e-7e2d-455a-9a21-a947d859a0dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>70314038-0298-4811-a5b9-357699dec26a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtNamaToko' and @placeholder = 'Input store name' and @name = 'txtNamaToko']</value>
      <webElementGuid>bd825034-6223-4580-9f78-485b5bf8a6b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
