<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Toko_txtNamaToko</name>
   <tag></tag>
   <elementGuidId>e086a9a6-3dc2-4418-abbb-2471b2cdf2fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtNamaToko']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtNamaToko</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b71ffe7-2137-441e-b63d-cf255d30d199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5c2280d8-3c06-4bac-9676-af54f6fb6674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNamaToko</value>
      <webElementGuid>71acf76a-23b9-464d-9546-9c6d5081534d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>55c5049d-9d4c-4ca1-b1a7-53716fe163ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input store name</value>
      <webElementGuid>4b289062-5782-425c-9e14-d9d4c0630949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtNamaToko</value>
      <webElementGuid>283828ab-9c28-4805-a6f0-870e8ebc1ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Samsung Dept Store</value>
      <webElementGuid>c4bb73ec-45ae-4d4b-8644-b8ebcdc6ad31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtNamaToko&quot;)</value>
      <webElementGuid>c39631ab-3c14-4113-9d2f-d1fbe50da5eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtNamaToko']</value>
      <webElementGuid>7618ceb7-4efa-405c-9a2d-9f1be74e3739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmToko']/div[3]/div/div/input</value>
      <webElementGuid>d3ae7e61-ed6f-4796-9b1f-0b8ce3b3eb6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3c0a9192-f1fc-46c6-a0a7-cfa94eb2c45c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtNamaToko' and @placeholder = 'Input store name' and @name = 'txtNamaToko']</value>
      <webElementGuid>24958e51-5ab5-4a00-bd2e-a5321789a1ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
