<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dealer Code_txtDealerCode</name>
   <tag></tag>
   <elementGuidId>7e66a25d-acd1-4f51-a910-98fa4ae1b533</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtDealerCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtDealerCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ff3a989-635a-4138-8032-ae9716fa9f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>833b81f1-1e75-4a7e-83ee-ab176e4015fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDealerCode</value>
      <webElementGuid>d5852a4d-7a46-4dee-8e23-67b72b15226d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input dealer code</value>
      <webElementGuid>3fd55734-3f30-48e3-8489-f1b9df3f749e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d6f33c69-5ee8-42aa-be14-b38c1b07e63c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDealerCode</value>
      <webElementGuid>10c3de2d-9d94-48a4-91b4-a3f52de32c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TC</value>
      <webElementGuid>20920869-a508-418f-a918-e71d8acf781f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDealerCode&quot;)</value>
      <webElementGuid>7f268aee-799c-40bb-9eb5-030504fac2bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtDealerCode']</value>
      <webElementGuid>c73e66a2-e093-4e33-a32f-06d3aa3548fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmToko']/div[6]/div/div/input</value>
      <webElementGuid>66039e82-3e87-4cd0-9db4-cebb54c2e9c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>d78fe98f-4485-4ced-8aa4-c211278dd4aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtDealerCode' and @placeholder = 'Input dealer code' and @name = 'txtDealerCode']</value>
      <webElementGuid>dae31fb6-1138-40a4-bc8a-af060a1eeccc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
