<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TransmartPanasonicPolytronAsusSamsun_e34999</name>
   <tag></tag>
   <elementGuidId>485abaf0-68ca-4186-8f71-43c5f44982f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='comboBoxMerchant']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#comboBoxMerchant</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>29e472c4-4c8f-4755-a4da-7d1186618a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control</value>
      <webElementGuid>b6f1da77-f613-43c7-8609-5b5c95ee627e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comboBoxMerchant</value>
      <webElementGuid>1e8ddacb-c152-4c84-996c-28c698bb6288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>comboBoxMerchant</value>
      <webElementGuid>789aa992-2928-4d60-96f0-c80a44457908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TransmartPanasonicPolytronAsusSamsungErafoneTesting 1Testing 2AVVBBBBBTGGGGTransmartttessstewsfToko Furniture Centretesttestaadfsdsdgfegeegbhbnth</value>
      <webElementGuid>143f0834-8460-442f-a4a3-4eefc2b4cefe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comboBoxMerchant&quot;)</value>
      <webElementGuid>2a72db84-9a4a-4590-9740-414d8e0966d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='comboBoxMerchant']</value>
      <webElementGuid>d18125cb-08ee-49e1-8264-510f9d549d07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmToko']/div/div/div/select</value>
      <webElementGuid>ac4d05b2-379c-44b3-ba84-ec675581660b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merchant'])[1]/following::select[1]</value>
      <webElementGuid>a6e472b6-8f2d-4d14-b7c8-43663b109d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Toko BliCicil Admin as'])[1]/following::select[1]</value>
      <webElementGuid>b58bc0fc-c739-4f4f-af90-df71486e566f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/preceding::select[1]</value>
      <webElementGuid>4a8a1d13-57c4-4bdb-a8b1-66976208d062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Toko'])[1]/preceding::select[2]</value>
      <webElementGuid>862ed53c-a062-4c04-b974-d91916b57848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>f1649c4b-0d0c-4baa-b450-13392c44676d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'comboBoxMerchant' and @name = 'comboBoxMerchant' and (text() = 'TransmartPanasonicPolytronAsusSamsungErafoneTesting 1Testing 2AVVBBBBBTGGGGTransmartttessstewsfToko Furniture Centretesttestaadfsdsdgfegeegbhbnth' or . = 'TransmartPanasonicPolytronAsusSamsungErafoneTesting 1Testing 2AVVBBBBBTGGGGTransmartttessstewsfToko Furniture Centretesttestaadfsdsdgfegeegbhbnth')]</value>
      <webElementGuid>7233551b-7b76-4bbf-9f4e-35cd2a5fd014</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
