<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Desc_txtDesc</name>
   <tag></tag>
   <elementGuidId>3db04aea-2250-4898-951f-c355f55c37dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtDesc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtDesc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5405fbfc-27c8-4bea-a929-18da57947742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDesc</value>
      <webElementGuid>bc43e0be-bec8-4b06-9c73-bf947b0840a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ecbdc4d0-9ec0-4bf0-81e0-82cdaafde54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan deskripsi notifikasi</value>
      <webElementGuid>3c78d2ab-3663-4057-9d20-f1f787fbd9da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDesc</value>
      <webElementGuid>46056412-8520-4492-8956-61df15409d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDesc&quot;)</value>
      <webElementGuid>e111bc3c-89a3-4aff-9467-73c994ae7d15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txtDesc']</value>
      <webElementGuid>7d8ef564-dbd1-4922-b56e-9949a789a3d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmProduct']/div[2]/div/div/textarea</value>
      <webElementGuid>9204ffa3-75b5-4349-a8e7-f05f55459983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>db6c7f4f-be89-44e7-afd5-65fe2a1268d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'txtDesc' and @placeholder = 'Masukkan deskripsi notifikasi' and @name = 'txtDesc']</value>
      <webElementGuid>64ce956e-a179-473a-8cc6-ef614a051b5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
