<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Product Desc_txtProductDesc</name>
   <tag></tag>
   <elementGuidId>095e6bb4-4598-4fc7-a0f5-072e80b42bf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtProductDesc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtProductDesc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>678ecf86-2139-42c4-8983-980c3254c398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f4b7dc7d-4dca-456d-adbb-9b8f452891fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtProductDesc</value>
      <webElementGuid>bf5eb028-f25f-4260-a94a-f85f279e0b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d67d66e8-3da0-4098-9feb-e75bfbe47461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtProductDesc</value>
      <webElementGuid>daf54c7f-a7b6-48b4-9e62-3ced292502ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan deskripsi produk</value>
      <webElementGuid>f36576d2-308b-4322-9edf-604ffb962d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtProductDesc&quot;)</value>
      <webElementGuid>72a008d5-ef68-47c8-a69f-820b4c93eb1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtProductDesc']</value>
      <webElementGuid>2f9db37a-f222-4caa-9a92-7104a41d30af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmProduct']/div[4]/div/div/input</value>
      <webElementGuid>9ca82fe2-14e3-4367-b0e0-070ac0072c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>fb570db1-b046-47c9-a204-8a331ad0493c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtProductDesc' and @name = 'txtProductDesc' and @placeholder = 'Masukkan deskripsi produk']</value>
      <webElementGuid>c4c7a763-e85d-4b00-86db-eb29ca98662d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
