<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_( 40 x 40 px )_txtProductImage</name>
   <tag></tag>
   <elementGuidId>2cdbb44a-6467-4be5-856d-06b4cfafd780</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtProductImage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[3]/div[2]/section/div/div/div/div[2]/form/div[1]/div[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75e41d47-b77b-41c6-8761-789ada60d56c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>358e3761-2c9c-4cdf-bf2b-7130b2147436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-file-input</value>
      <webElementGuid>942448f6-79b4-4f83-bcba-a292e3d199cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtProductImage</value>
      <webElementGuid>9072d9bb-8fb0-4a1e-b977-93f001ce01ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtProductImage</value>
      <webElementGuid>04456c1f-9bca-44ad-837f-d3e658d45938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>image/*</value>
      <webElementGuid>25bfd260-5238-4fe4-97cb-320a5c19fba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>onFileChange('txtProductImage', 'ProductImage', 40, 40)</value>
      <webElementGuid>c29d6122-4079-46a5-b672-80c00d01e169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtProductImage&quot;)</value>
      <webElementGuid>3f425b02-b5f5-4a27-86f3-c813f13927a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtProductImage']</value>
      <webElementGuid>b580e366-134f-4045-943b-80767e475415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmProduct']/div/div[2]/div/input</value>
      <webElementGuid>589b4ced-9584-4264-a33a-6e08c8fc1d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>486d507f-5301-4114-9c02-3bbed01e0b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'txtProductImage' and @name = 'txtProductImage']</value>
      <webElementGuid>3a4bbc69-e7cf-472e-812c-7f0e21be54fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
