<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Toko_txtNamaToko</name>
   <tag></tag>
   <elementGuidId>23c9d707-8ac8-4fda-841d-3189c1a39182</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtNamaToko</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtNamaToko']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31d6916c-a8a9-41f5-8c09-fe05afa70a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f910143c-63d1-4557-b515-2c830bbc096a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNamaToko</value>
      <webElementGuid>0593aab3-a178-43c5-944f-a5db22271ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c4db564f-0a21-48bf-99d5-ad291d7b950d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input store name</value>
      <webElementGuid>4c471273-46ea-405e-b9e3-e49f0117d208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtNamaToko</value>
      <webElementGuid>421d8461-17b5-4dca-adf5-81c0eee3669c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtNamaToko&quot;)</value>
      <webElementGuid>a4f9b037-1458-4839-8582-84c80279ce4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtNamaToko']</value>
      <webElementGuid>71a324b5-47e5-4a36-a841-c72965793b51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmToko']/div[3]/div/div/input</value>
      <webElementGuid>386f7c56-a37e-454c-b9dd-66e90b8082c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e8364066-49d3-41fc-8b83-4fef412c6f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtNamaToko' and @placeholder = 'Input store name' and @name = 'txtNamaToko']</value>
      <webElementGuid>0a0bce03-3af4-4eae-a5a0-c5bdb0f4f07b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
