<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_lalaland</name>
   <tag></tag>
   <elementGuidId>26ef387e-0d1e-4789-9f2e-616edaed5acf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lalaland</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lalaland']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ec7e71a-93d4-4967-a6bd-af627622f002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c9e0ea6d-a082-42ba-a467-3e5f9da8c563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lalaland</value>
      <webElementGuid>67e03421-4d10-49be-aacd-43ff4ec94cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b8fd6b56-21e6-4fd4-97e8-bebdbfe79126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan email</value>
      <webElementGuid>4c268e18-1601-4f44-adb9-2f64df1d2721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b3143ea6-a2f7-422c-8683-11905e436356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lalaland</value>
      <webElementGuid>1690eec5-ac37-4f73-869f-deb92219c169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.removeAttribute('readonly');</value>
      <webElementGuid>af17766f-c990-4b27-8931-851b7cf5c08a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Fredi@megafinance.co.id</value>
      <webElementGuid>fc335290-e778-493d-b5d3-a50481a87896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lalaland&quot;)</value>
      <webElementGuid>fe1450f7-6037-4dde-8ef2-06c2a45d124a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lalaland']</value>
      <webElementGuid>ff3bcbcc-0bad-41a0-947e-fb396ef1d811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmProduct']/div[2]/div/div/input</value>
      <webElementGuid>350c59d0-2eb2-4d1c-8393-725d687486ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>5974e49e-9c0a-4f71-bda3-013d81bc38d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'lalaland' and @placeholder = 'Masukkan email' and @name = 'lalaland']</value>
      <webElementGuid>b43ab06e-748b-4d51-adbe-58b0acf2029a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
