<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_5</name>
   <tag></tag>
   <elementGuidId>f1f88dc0-ac35-4b85-92fb-e21eb5899705</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(6) > a.page-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='pagination-demo']/li[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7780df97-a8ce-43a8-95c3-07dadb9fd089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#page-5</value>
      <webElementGuid>7b1e6935-1ebd-402b-8503-26191bbe11b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-link</value>
      <webElementGuid>748df5e3-45d7-4ca0-ac98-7307b945577c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>1fdd1adf-348b-4c79-9beb-9360ca3ebdc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pagination-demo&quot;)/li[6]/a[@class=&quot;page-link&quot;]</value>
      <webElementGuid>d4f9d56f-26bb-4735-b4ad-45db14a54cd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pagination-demo']/li[6]/a</value>
      <webElementGuid>7a2d3c7c-74fa-4a52-ae65-a64830fa7141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'5')]</value>
      <webElementGuid>500a32bc-bf63-49ed-bc20-3012e1720ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prev'])[1]/following::a[4]</value>
      <webElementGuid>fa230864-f0f6-41c8-8c2a-29e8e7265093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 10 of 10 entries'])[1]/following::a[4]</value>
      <webElementGuid>e079307b-02a9-42ea-b7ed-26683812292b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='…'])[1]/preceding::a[1]</value>
      <webElementGuid>161fac0d-400b-42dd-886d-865bf07522dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::a[3]</value>
      <webElementGuid>a6c50702-f869-45bc-8cf5-c6eac049ac2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#page-5')]</value>
      <webElementGuid>334f7a15-3f0b-4edc-b97e-6aab95de0c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[3]/ul/li[6]/a</value>
      <webElementGuid>6ba5da36-fbd8-476d-a45a-e05814a0fed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#page-5' and (text() = '5' or . = '5')]</value>
      <webElementGuid>9479c721-f724-41de-aa9f-9e4b86f3497e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
