<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_List of Customers_filterSearch</name>
   <tag></tag>
   <elementGuidId>2c532d58-3bec-497d-884f-038fe74cf4f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filterSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filterSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9be9a20f-ab04-44aa-b1a0-d336331fbfbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>70aa79c2-7e95-47fc-aa01-a01bc4c870a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filterSearch</value>
      <webElementGuid>3c42af87-4c9a-4ac5-bf8f-a097185b0cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8defca1f-b278-4877-9a48-71c3584c969a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan keyword   </value>
      <webElementGuid>23cc3bc9-0e27-42c3-96f6-545a3d6e8eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filterSearch</value>
      <webElementGuid>f36f4f2b-193f-47a5-a9dd-f4d66e4de2f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterSearch&quot;)</value>
      <webElementGuid>75436ad4-ff75-4cee-bfab-2b2d47d22334</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filterSearch']</value>
      <webElementGuid>797fc3bf-183d-40a9-beee-ae0ebbbebfaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='complex-header-datatable']/div/div/div/div[2]/div/div[2]/div[2]/div/input</value>
      <webElementGuid>a85f718e-c9c3-499d-adc7-cedfef9e7098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>de2c5907-75dc-4813-8f6d-c6d1fd0edf80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'filterSearch' and @placeholder = 'Masukkan keyword   ' and @name = 'filterSearch']</value>
      <webElementGuid>eb23845e-cef2-4d59-929a-b33848b11df3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
