<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Show                                _69175e</name>
   <tag></tag>
   <elementGuidId>0d341c1c-1baa-4dd1-b645-06b04a5cf936</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filterLimit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='filterLimit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c00ee105-d846-427b-88f9-bbf4cddfd70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filterLimit</value>
      <webElementGuid>030e0885-72c5-47bf-acce-d294dd8700f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filterLimit</value>
      <webElementGuid>99e2951b-33e8-40a1-be03-3d4e300aa2d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>58471ca3-0f2a-45ad-9de4-158de9e46903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>onFilterChangeCallApi(true)</value>
      <webElementGuid>d4558863-9c5d-461a-a2cf-7e8db07463ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                Show
                                                5
                                                10
                                                25
                                                50
                                                100
                                                500
                                                1000
                                            </value>
      <webElementGuid>c1458405-6e97-4043-80f6-f25c10697e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterLimit&quot;)</value>
      <webElementGuid>23309150-8755-4a5d-b8a4-19824512ca44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='filterLimit']</value>
      <webElementGuid>c65928d2-d215-41b1-bed9-2f1b6b60c115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='complex-header-datatable']/div/div/div/div[2]/div/div/div/select</value>
      <webElementGuid>8f1f5ff0-6442-4fd2-8a0b-b32d34b28203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List of Customers'])[1]/following::select[1]</value>
      <webElementGuid>58bf81f9-a6ff-4348-b86f-1a3d4ed2a7ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Management'])[2]/following::select[1]</value>
      <webElementGuid>9d07292e-bb8a-4c3b-a0a6-03c8fa6599dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[1]/preceding::select[3]</value>
      <webElementGuid>028745f4-94bc-4015-a268-aed3df2d8e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>db86f97c-be7e-4ef8-9957-c503cd0317f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'filterLimit' and @id = 'filterLimit' and (text() = '
                                                Show
                                                5
                                                10
                                                25
                                                50
                                                100
                                                500
                                                1000
                                            ' or . = '
                                                Show
                                                5
                                                10
                                                25
                                                50
                                                100
                                                500
                                                1000
                                            ')]</value>
      <webElementGuid>7edf3ef9-00a2-41e3-9508-7b8cfd9d0569</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
