<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Show                                _69175e</name>
   <tag></tag>
   <elementGuidId>f3661e39-99d0-4337-8a5a-8e1e206de594</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filterLimit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='filterLimit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ff38b898-ec45-4673-bb50-91d0d613741f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filterLimit</value>
      <webElementGuid>cb996059-90e1-47c7-89ea-85aa4406ae63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filterLimit</value>
      <webElementGuid>82c7dbdf-ec4f-45a2-9da7-b8f63cf3138e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4430e178-e523-4f7a-b5d9-920eec4c62f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>onFilterChangeCallApi(true)</value>
      <webElementGuid>7537e3a0-10bf-4536-aa45-58404712b1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                Show
                                                5
                                                10
                                                25
                                                50
                                                100
                                                500
                                                1000
                                            </value>
      <webElementGuid>47b9885a-6d8b-467c-abce-0b558e406d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterLimit&quot;)</value>
      <webElementGuid>327ecda6-d4c4-4e56-b180-011f5731e0ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='filterLimit']</value>
      <webElementGuid>1fe8a806-8876-47bd-94ff-6a0829b8af0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='complex-header-datatable']/div/div/div/div[2]/div/div/div/select</value>
      <webElementGuid>7e133edc-d575-4f8e-b582-2cfbf9b965b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List of Customers'])[1]/following::select[1]</value>
      <webElementGuid>e3c44172-2572-425b-b384-29ff515be7a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Management'])[2]/following::select[1]</value>
      <webElementGuid>e6a8f0a6-3a3d-4cae-8cc0-a559fc2746e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[1]/preceding::select[3]</value>
      <webElementGuid>8ff4687f-3138-4987-94fd-92ee44f50985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>3d0cf25d-64d8-43dc-8a18-d582700dc446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'filterLimit' and @id = 'filterLimit' and (text() = '
                                                Show
                                                5
                                                10
                                                25
                                                50
                                                100
                                                500
                                                1000
                                            ' or . = '
                                                Show
                                                5
                                                10
                                                25
                                                50
                                                100
                                                500
                                                1000
                                            ')]</value>
      <webElementGuid>edf471e6-7ad3-42e1-9770-6284904c42dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
