<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nonactive</name>
   <tag></tag>
   <elementGuidId>50fcdbcf-df42-4ebc-905a-6b946852c040</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.badge.badge-danger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tbl-administrator']/tbody/tr[2]/td[6]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7ad3dec4-c449-450d-abc3-9af7b6de84ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>badge badge-danger</value>
      <webElementGuid>ec55f374-cda5-4c76-875b-368100704832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nonactive</value>
      <webElementGuid>72ffab9f-7c37-42cf-b240-8b395ba5c00e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl-administrator&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[6]/div[@class=&quot;badge badge-danger&quot;]</value>
      <webElementGuid>7dc65df7-f9a4-4960-991b-669cc0662acb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbl-administrator']/tbody/tr[2]/td[6]/div</value>
      <webElementGuid>4d2b4c77-10ef-43f9-84a5-190b34f0db9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fredi@megafinance.co.id'])[1]/following::div[1]</value>
      <webElementGuid>81c4fd30-35d4-434f-9cc1-9d9ad620abef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fredi Bong'])[1]/following::div[1]</value>
      <webElementGuid>e5595f19-5147-4439-972e-70c837619454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activate'])[1]/preceding::div[1]</value>
      <webElementGuid>e0d786b9-aa47-45a4-95a3-571008b19560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privilege'])[2]/preceding::div[1]</value>
      <webElementGuid>80444d3c-2cb4-4364-add5-3af80033c49c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nonactive']/parent::*</value>
      <webElementGuid>45b9821c-d5aa-47c5-9ec6-a954cfc034c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[6]/div</value>
      <webElementGuid>903d8a5e-4da0-4b62-b3b2-5610ca0cf042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Nonactive' or . = 'Nonactive')]</value>
      <webElementGuid>8691035c-7f97-4244-a287-bb43ca9b5626</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
