<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Status                              _ebcc15</name>
   <tag></tag>
   <elementGuidId>2f9db9af-74e0-46ab-9735-24d672911499</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filterStatus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='filterStatus']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>89e9f486-cd51-4ad8-bfb0-10ef2cebe2f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filterStatus</value>
      <webElementGuid>984745f7-7f0d-4b61-b30f-ab7a2c3b1f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filterStatus</value>
      <webElementGuid>d02463de-d677-470f-8e85-63cd58f6e05c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e99a11be-f672-46b8-aa1a-7552ae8d74f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>onStatusChange()</value>
      <webElementGuid>8b72c4a2-93fa-4215-b6cb-287f9f97b576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                Status
                                                Semua
                                                Selesai
                                                Proses
                                                Transaksi
                                                TTD Kontrak
                                                Ditolak
                                                Dibatalkan
                                            </value>
      <webElementGuid>41e49249-21ef-4f77-a0f5-7ef660f097c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterStatus&quot;)</value>
      <webElementGuid>0760d4b8-e264-4a8d-81aa-c105f04c4d7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='filterStatus']</value>
      <webElementGuid>0839416d-7f6c-4469-b30f-27f907f90bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='complex-header-datatable']/div/div/div/div[2]/div/div/div[2]/select</value>
      <webElementGuid>6cff29d3-1933-413b-a6a2-1f4027a19b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List Motorcycle Transaction BliCicil Admin as'])[1]/following::select[1]</value>
      <webElementGuid>76b9e5cb-46d0-4d2b-83c0-a9ab20b9c4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Motorcycle'])[2]/following::select[1]</value>
      <webElementGuid>3f1de574-04fb-4a80-b049-ea8b31f6c3d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[1]/preceding::select[1]</value>
      <webElementGuid>342ae17c-cc46-4d2e-90d2-a71e81803256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Date &amp; Time'])[1]/preceding::select[1]</value>
      <webElementGuid>18fd97c0-6049-4b18-9ded-fe970c48978c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>336582a7-5e18-49e5-85c8-535b6c3dbcc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'filterStatus' and @id = 'filterStatus' and (text() = '
                                                Status
                                                Semua
                                                Selesai
                                                Proses
                                                Transaksi
                                                TTD Kontrak
                                                Ditolak
                                                Dibatalkan
                                            ' or . = '
                                                Status
                                                Semua
                                                Selesai
                                                Proses
                                                Transaksi
                                                TTD Kontrak
                                                Ditolak
                                                Dibatalkan
                                            ')]</value>
      <webElementGuid>c2f2dbaa-d692-4cc5-9103-3f0df50ce5b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
