<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span</name>
   <tag></tag>
   <elementGuidId>f91ffa50-7117-4158-bb3f-f301130068c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.next.available > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d4bd84f9-9a7f-4493-a2e1-6b13f9ce7ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;loaded&quot;]/body[@class=&quot;vertical-layout vertical-menu-modern navbar-floating footer-static  menu-expanded pace-done&quot;]/div[@class=&quot;daterangepicker ltr show-ranges show-calendar opensright&quot;]/div[@class=&quot;drp-calendar right&quot;]/div[@class=&quot;calendar-table&quot;]/table[@class=&quot;table-condensed&quot;]/thead[1]/tr[1]/th[@class=&quot;next available&quot;]/span[1]</value>
      <webElementGuid>dad94749-1cdf-40c3-a9cb-21c32de90354</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/span</value>
      <webElementGuid>1aa03dbd-ed7e-40a6-ae33-27fda618f3fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
