<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Proses_rotate-icon-64901e74c58fba0dae4dff85</name>
   <tag></tag>
   <elementGuidId>106c5624-a8c4-4917-96fc-6226c0139ceb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rotate-icon-64901e74c58fba0dae4dff85</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Proses'])[2]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>12611c6f-9816-43e4-add1-618b9527eb17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>b21a34c1-3d53-4b93-9d81-cbbcf17e5a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rotate-icon-64901e74c58fba0dae4dff85</value>
      <webElementGuid>495d72cc-815f-4ebc-b4ce-d1e1b067c959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>toggleIcon('64901e74c58fba0dae4dff85', false)</value>
      <webElementGuid>17106609-040c-4670-a669-5c0530933ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>b3a02cef-0c9a-4e71-8a6d-d0b019b89a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 12 12</value>
      <webElementGuid>66da113f-61bf-4da0-9219-20547fc1390a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>49a30a35-d639-429f-a408-2df4cdcbeed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>9f4b0ea7-eb09-41ca-af82-011f6a13d2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rotate-icon-64901e74c58fba0dae4dff85&quot;)</value>
      <webElementGuid>823f91bd-61c3-44c5-97d9-a69e7d86e9b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proses'])[2]/following::*[name()='svg'][1]</value>
      <webElementGuid>821b3314-e313-4c72-beda-1dc859e441a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/following::*[name()='svg'][1]</value>
      <webElementGuid>cda81713-e855-4e3f-9c3a-94130bfba198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jun 19 2023 - 5:30PM'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>56111f00-e2a3-459c-b333-3c208552165b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[3]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>f072678f-1cf3-4458-b42a-b31eb014c68a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//svg[@id = 'rotate-icon-64901e74c58fba0dae4dff85']</value>
      <webElementGuid>25929adc-35a6-40e8-90e3-846ce124b53e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
