<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Proses_rotate-icon-61e28a1d1dac201b017d5bf7</name>
   <tag></tag>
   <elementGuidId>abb5730f-b5b1-4376-96e1-7da12abf8dab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rotate-icon-61e28a1d1dac201b017d5bf7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Proses'])[2]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>ed13d5f2-9041-4a93-bfa2-02de8f6bd51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>8ae9e6ea-a197-493a-bd81-4316d422daa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rotate-icon-61e28a1d1dac201b017d5bf7</value>
      <webElementGuid>6b99d3be-3415-4459-9bef-94c7f821f694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>toggleIcon('61e28a1d1dac201b017d5bf7', false)</value>
      <webElementGuid>9786ab15-80e3-4b44-b8cd-fa33b1f393b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>8d9f968a-b952-4045-b0f5-0b235925d15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 12 12</value>
      <webElementGuid>456b1c4c-0092-4319-83ce-1ce304cb3963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>671bfb84-ed27-4b06-aaf2-fa2387e547d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>20d40d5d-364b-485b-b9a0-37ba5f716f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rotate-icon-61e28a1d1dac201b017d5bf7&quot;)</value>
      <webElementGuid>2da883c1-ae55-4f97-bb80-beee90bf9ce7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proses'])[2]/following::*[name()='svg'][1]</value>
      <webElementGuid>462da3d2-af8d-4aa0-9642-486cea4833cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/following::*[name()='svg'][1]</value>
      <webElementGuid>dd764a89-3cdb-4e8d-9527-9f0a59bc3030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jan 16 2022 - 4:24AM'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>b43bf6d9-5c31-4c35-b08a-a64d79482ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[3]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>37a905f5-dd44-47cc-82ad-32fa810013ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//svg[@id = 'rotate-icon-61e28a1d1dac201b017d5bf7']</value>
      <webElementGuid>3d49c167-de8b-4da7-a0e6-58c38a2daeee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
