<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>body_deskripsi</name>
   <tag></tag>
   <elementGuidId>b1f91681-97f8-4d8e-933d-f8e5141ff07e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body.cke_editable.cke_editable_themed.cke_contents_ltr.cke_show_borders</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[@class=&quot;cke_editable cke_editable_themed cke_contents_ltr cke_show_borders&quot;][count(. | //body[@contenteditable = 'true' and @class = 'cke_editable cke_editable_themed cke_contents_ltr cke_show_borders' and @spellcheck = 'false' and (text() = 'Untuk cek status sisa angsuran dan pembayaran, kamu dapat mengakses menu Pinjaman pada aplikasi Blicicil.Sebagai alternatif, kamu juga dapat mengikuti langkah-langkah di bawah ini:Akses WhatsApp Mega Finance wa.me/6281315316395 atau Live Chat di aplikasi BlicicilKetikan HaloKetikan 8 - Cek Sisa Angsuran atau 9 - Cek PembayaranIkuti tahap selanjutnya/html[1]/body[@class=&quot;cke_editable cke_editable_themed cke_contents_ltr cke_show_borders&quot;]' or . = 'Untuk cek status sisa angsuran dan pembayaran, kamu dapat mengakses menu Pinjaman pada aplikasi Blicicil.Sebagai alternatif, kamu juga dapat mengikuti langkah-langkah di bawah ini:Akses WhatsApp Mega Finance wa.me/6281315316395 atau Live Chat di aplikasi BlicicilKetikan HaloKetikan 8 - Cek Sisa Angsuran atau 9 - Cek PembayaranIkuti tahap selanjutnya/html[1]/body[@class=&quot;cke_editable cke_editable_themed cke_contents_ltr cke_show_borders&quot;]')]) = count(//body[@contenteditable = 'true' and @class = 'cke_editable cke_editable_themed cke_contents_ltr cke_show_borders' and @spellcheck = 'false' and (text() = 'Untuk cek status sisa angsuran dan pembayaran, kamu dapat mengakses menu Pinjaman pada aplikasi Blicicil.Sebagai alternatif, kamu juga dapat mengikuti langkah-langkah di bawah ini:Akses WhatsApp Mega Finance wa.me/6281315316395 atau Live Chat di aplikasi BlicicilKetikan HaloKetikan 8 - Cek Sisa Angsuran atau 9 - Cek PembayaranIkuti tahap selanjutnya/html[1]/body[@class=&quot;cke_editable cke_editable_themed cke_contents_ltr cke_show_borders&quot;]' or . = 'Untuk cek status sisa angsuran dan pembayaran, kamu dapat mengakses menu Pinjaman pada aplikasi Blicicil.Sebagai alternatif, kamu juga dapat mengikuti langkah-langkah di bawah ini:Akses WhatsApp Mega Finance wa.me/6281315316395 atau Live Chat di aplikasi BlicicilKetikan HaloKetikan 8 - Cek Sisa Angsuran atau 9 - Cek PembayaranIkuti tahap selanjutnya/html[1]/body[@class=&quot;cke_editable cke_editable_themed cke_contents_ltr cke_show_borders&quot;]')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>8ef26448-9be7-476b-ae89-6efb2b393678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>70ebeb2f-64b9-46f4-9c63-7ee38aafc0b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cke_editable cke_editable_themed cke_contents_ltr cke_show_borders</value>
      <webElementGuid>b5a7fddd-fbab-40bd-8488-e734bec38adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c784b3b8-5929-46cb-ab67-350ccd6323b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Untuk cek status sisa angsuran dan pembayaran, kamu dapat mengakses menu Pinjaman pada aplikasi Blicicil.Sebagai alternatif, kamu juga dapat mengikuti langkah-langkah di bawah ini:Akses WhatsApp Mega Finance wa.me/6281315316395 atau Live Chat di aplikasi BlicicilKetikan HaloKetikan 8 - Cek Sisa Angsuran atau 9 - Cek PembayaranIkuti tahap selanjutnya/html[1]/body[@class=&quot;cke_editable cke_editable_themed cke_contents_ltr cke_show_borders&quot;]</value>
      <webElementGuid>3630b576-6c65-4e4e-b480-1f89cfe41e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cke_editable cke_editable_themed cke_contents_ltr cke_show_borders&quot;]</value>
      <webElementGuid>1ef5025f-2a01-4ae5-8467-d498c58b9c37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
      <webElementGuid>cad11698-6941-4cd0-9712-0285b622b698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//body[(text() = 'Untuk cek status sisa angsuran dan pembayaran, kamu dapat mengakses menu Pinjaman pada aplikasi Blicicil.Sebagai alternatif, kamu juga dapat mengikuti langkah-langkah di bawah ini:Akses WhatsApp Mega Finance wa.me/6281315316395 atau Live Chat di aplikasi BlicicilKetikan HaloKetikan 8 - Cek Sisa Angsuran atau 9 - Cek PembayaranIkuti tahap selanjutnya/html[1]/body[@class=&quot;cke_editable cke_editable_themed cke_contents_ltr cke_show_borders&quot;]' or . = 'Untuk cek status sisa angsuran dan pembayaran, kamu dapat mengakses menu Pinjaman pada aplikasi Blicicil.Sebagai alternatif, kamu juga dapat mengikuti langkah-langkah di bawah ini:Akses WhatsApp Mega Finance wa.me/6281315316395 atau Live Chat di aplikasi BlicicilKetikan HaloKetikan 8 - Cek Sisa Angsuran atau 9 - Cek PembayaranIkuti tahap selanjutnya/html[1]/body[@class=&quot;cke_editable cke_editable_themed cke_contents_ltr cke_show_borders&quot;]')]</value>
      <webElementGuid>962d53b9-11f3-4b01-94d9-d8fe2a6479b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
