<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Press ALT 0 for help_cke_wysiwyg_fra_043255</name>
   <tag></tag>
   <elementGuidId>192d8886-f499-4cb6-871b-32533182006e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.cke_wysiwyg_frame.cke_reset</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cke_1_contents']/iframe</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[@class=&quot;cke_editable cke_editable_themed cke_contents_ltr cke_show_borders&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>082e40aa-a4f4-4951-9001-8a354b8d5de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>846db902-0704-4dad-bfa1-f5a66e176a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cke_editable cke_editable_themed cke_contents_ltr cke_show_borders</value>
      <webElementGuid>3ebce822-a5b4-4ab2-900b-f06d403b5f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Rich Text Editor, txaContent</value>
      <webElementGuid>44253b4f-ab36-4862-ba10-e4308ffdca01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cke_80</value>
      <webElementGuid>65bdefae-e936-4a25-8431-7e8bd297280e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>14b1c447-2cac-4dd7-a0bc-d9d277505a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5837b9dc-1798-4975-a632-82427c57a95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cke_editable cke_editable_themed cke_contents_ltr cke_show_borders&quot;]</value>
      <webElementGuid>ee0e37be-a242-478b-8f9d-cc24ccdec42c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Untuk cek status sisa angsuran dan pembayaran, kamu dapat mengakses menu Pinjaman pada aplikasi Blicicil.Sebagai alternatif, kamu juga dapat mengikuti langkah-langkah di bawah ini:Akses WhatsApp Mega Finance wa.me/6281315316395 atau Live Chat di aplikasi BlicicilKetikan HaloKetikan 8 - Cek Sisa Angsuran atau 9 - Cek PembayaranIkuti tahap selanjutnya/html[1]/body[@class=&quot;cke_editable cke_editable_themed cke_contents_ltr cke_show_borders&quot;]</value>
      <webElementGuid>4e0f8c75-ec31-4d32-89eb-f8ab86049b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5a56f85e-afa1-4b23-8423-54ff6f017f9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cke_1_contents']/iframe</value>
      <webElementGuid>b10dab85-2b89-4a56-b9b4-7e68a82d1466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>ffd753f9-6ec7-4732-8863-7c0d23431d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Rich Text Editor, txaContent']</value>
      <webElementGuid>0761972b-9316-413b-bf5a-4f44944326f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
