<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Selesai_rotate-icon-628c89634a0767038c118b4f</name>
   <tag></tag>
   <elementGuidId>9c9ddc19-b3f1-4805-85fa-b8a3a2dc4914</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rotate-icon-628c89634a0767038c118b4f</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Selesai'])[2]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>4cc6b9d2-127c-4a94-bcb1-3534320525a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>eb765429-50c0-474c-b52c-cb13766502e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rotate-icon-628c89634a0767038c118b4f</value>
      <webElementGuid>7c91db95-ec8f-47fa-b04f-0014e1ee4ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>toggleIcon('628c89634a0767038c118b4f', false)</value>
      <webElementGuid>7938d4df-3263-4de4-8822-11c4db53d742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>ea62e071-7d95-472d-aee8-c0e288cee8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 12 12</value>
      <webElementGuid>8834aa23-3e32-4ef5-9254-ba3195c26457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>5dac5939-c92f-49dd-9aa6-52dbb71a1c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>d817d7d7-b55d-45d0-a3ec-481121262187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rotate-icon-628c89634a0767038c118b4f&quot;)</value>
      <webElementGuid>a2e85f83-3073-40cd-8777-313e85b6fd3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selesai'])[2]/following::*[name()='svg'][1]</value>
      <webElementGuid>3b7a0652-cf86-4faf-96f3-c27556f9f371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BGRCC00415'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>d10d07b8-9b40-4a01-83e5-1012fcee2a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='May 25 2022 - 9:44AM'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>e563c0c5-3eca-422b-bcf5-bf5e4c688815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>94ec3351-e705-4752-b6ae-2c67d08a6679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//svg[@id = 'rotate-icon-628c89634a0767038c118b4f']</value>
      <webElementGuid>50c72307-17f8-4590-ab66-5fe4a7ca6049</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
