<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Ditolak_rotate-icon-61e4c8d1b4aaa3728e4c8e32</name>
   <tag></tag>
   <elementGuidId>47051f79-9cb5-4e8a-a5b4-12362392c333</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rotate-icon-61e4c8d1b4aaa3728e4c8e32</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Ditolak'])[2]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>f88573f5-e9ce-4101-92a4-1680c37b5eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>130c92a7-68d9-49ac-a4c2-98e1ebe52568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rotate-icon-61e4c8d1b4aaa3728e4c8e32</value>
      <webElementGuid>60ad065a-9c3e-46c8-aefc-fb7e3add9ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>toggleIcon('61e4c8d1b4aaa3728e4c8e32', false)</value>
      <webElementGuid>92e6ef07-cc28-44b5-b314-cf017b752eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>50fa29ad-e8bd-4e25-9845-3cdaa77faefb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 12 12</value>
      <webElementGuid>b9445c44-b36f-43c1-8041-41a5e59dfc70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>6e1c0e94-dfa7-4e7d-aa9c-326e1b71ce59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>77c7fc30-be55-4f0a-9c90-20a26dc6f879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rotate-icon-61e4c8d1b4aaa3728e4c8e32&quot;)</value>
      <webElementGuid>6584515e-5094-4960-b03c-87514e7fe481</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ditolak'])[2]/following::*[name()='svg'][1]</value>
      <webElementGuid>c9b8a85a-b535-4aae-b71e-53f181af60f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BGRCC00035'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>0ce60be4-d98f-4468-b143-450a8b22beb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jan 17 2022 - 8:48AM'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>8c370bc6-78fb-4241-9b35-4a1a945628b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[16]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>9875aaf8-e649-4ed7-a9ec-612f8690d55b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//svg[@id = 'rotate-icon-61e4c8d1b4aaa3728e4c8e32']</value>
      <webElementGuid>0d6e9009-ae41-46ab-9f7c-16dd39771f06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
