<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_30,000,000</name>
   <tag></tag>
   <elementGuidId>2ac22dd4-3e50-49e8-a46e-3828346369e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tbl-motorcycle']/tbody/tr[5]/td[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>43aa5dee-98ba-4d9a-a268-9cff47349aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>30,000,000</value>
      <webElementGuid>7017b51d-9699-4b93-8d8f-a82cb61f790d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl-motorcycle&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[5]</value>
      <webElementGuid>1c286478-171f-4132-89dc-5163ea574e5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbl-motorcycle']/tbody/tr[5]/td[5]</value>
      <webElementGuid>dc0bf075-dd03-4126-9665-9d4fb01ed7f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BGRCB00182'])[1]/following::td[1]</value>
      <webElementGuid>b1b54c3d-26d0-48b5-9519-456df37ab64b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KURNIA RIADHI'])[1]/following::td[2]</value>
      <webElementGuid>3be7a79c-05c7-478c-8a60-73f468ddfa28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dibatalkan'])[5]/preceding::td[1]</value>
      <webElementGuid>0ac9db3c-3ad6-410f-9f40-6324e27eeb5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jul 8 2022 - 10:39AM'])[1]/preceding::td[3]</value>
      <webElementGuid>6e16719d-0549-43e7-89c3-4b798e7c2d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='30,000,000']/parent::*</value>
      <webElementGuid>7b61c744-0b01-44a3-b012-6c979dfe42ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[5]</value>
      <webElementGuid>b7d26402-2bb4-4f18-ab08-7b570e406ef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '30,000,000' or . = '30,000,000')]</value>
      <webElementGuid>01081ce5-ba9b-4384-8c1a-263440e9f7a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
