<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_uji wordings</name>
   <tag></tag>
   <elementGuidId>17920486-daa9-431b-aa90-fd5b9b080f82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtDesc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtDesc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7c2c1028-6f96-4fb6-b99c-cbf3d0b084d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDesc</value>
      <webElementGuid>2e93e9b7-4aa8-42c2-9217-736c2bc0f83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>738da610-1146-4e9c-9b3a-17ed2db039a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan deskripsi notifikasi</value>
      <webElementGuid>ea419448-eea4-49a4-b7a9-f8b8f565302b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDesc</value>
      <webElementGuid>b944c21b-c9a6-4842-aba8-754854fc7909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>uji wordings</value>
      <webElementGuid>1710b1a6-2bd1-4db5-821b-020b8c059a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDesc&quot;)</value>
      <webElementGuid>a259a1a0-bcf6-49d1-b588-e2ef7a0d0965</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txtDesc']</value>
      <webElementGuid>61d4da03-b5e5-4854-bf7e-f9a2f1784413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmProduct']/div[2]/div/div/textarea</value>
      <webElementGuid>58b4cb55-9ea5-4c44-aaf9-3f7a88d39c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desc'])[1]/following::textarea[1]</value>
      <webElementGuid>bb8070ea-aa88-4105-957e-161d954b9f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/following::textarea[1]</value>
      <webElementGuid>8fb5078f-71e4-48f2-972e-52123496f3a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location'])[1]/preceding::textarea[1]</value>
      <webElementGuid>2a6f2615-862f-41d2-8fc7-8082914aa2a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::textarea[1]</value>
      <webElementGuid>8129727b-fff0-43c3-81ad-e356b9951f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='uji wordings']/parent::*</value>
      <webElementGuid>b2770912-2c73-4540-854e-5b8e36e5498a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>de92c198-dd75-42d8-a9df-b187a0e1b73e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'txtDesc' and @placeholder = 'Masukkan deskripsi notifikasi' and @name = 'txtDesc' and (text() = 'uji wordings' or . = 'uji wordings')]</value>
      <webElementGuid>2e00fd34-1cbd-47af-9409-60ad6d7dff3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
