<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Password_input-group-text cursor-pointer</name>
   <tag></tag>
   <elementGuidId>e0aa6d18-e094-4a56-becd-50228c819421</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.input-group-text.cursor-pointer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmLogin']/div[2]/div[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>91cf63fd-b2fa-4507-a1d4-c27d070326f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-group-text cursor-pointer</value>
      <webElementGuid>21ec1adb-da33-40c5-aac2-f0ba51c0fff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmLogin&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;input-group input-group-merge form-password-toggle&quot;]/div[@class=&quot;input-group-append&quot;]/span[@class=&quot;input-group-text cursor-pointer&quot;]</value>
      <webElementGuid>89e2e828-9098-4d4f-81a1-00f055dcea22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmLogin']/div[2]/div[2]/div/span</value>
      <webElementGuid>b46a2ec3-95ad-4bd6-88ed-b456e3cf92d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::span[1]</value>
      <webElementGuid>bc32bc8d-142f-4dff-8dbe-912fea8a5b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::span[1]</value>
      <webElementGuid>7911d36e-ee29-46b5-bcc0-99888438ce0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::span[1]</value>
      <webElementGuid>f538ade4-4f4a-4fd0-9f9d-e8e07b432777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>db44ac5f-b53e-4aa0-90ab-646720a30f8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
