<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Show                                _69175e</name>
   <tag></tag>
   <elementGuidId>c3e53ac5-4029-49ed-b310-003b81e61571</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filterLimit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='filterLimit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f038defc-2a2d-4d24-94be-68d5059446e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filterLimit</value>
      <webElementGuid>5acf5aa8-5846-470f-b62e-266563c82e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filterLimit</value>
      <webElementGuid>139864df-0e6b-4c9e-bdfc-2752d324780d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2139a5eb-bf09-46c6-b336-689db8eaa4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>onFilterChangeCallApi(true)</value>
      <webElementGuid>a5f9a25c-3368-4b77-9d7e-3d6606682bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                Show
                                                5
                                                10
                                                25
                                                50
                                                100
                                                500
                                                1000
                                            </value>
      <webElementGuid>d4e09bc7-4abd-45b3-a159-e135c3a8c0cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterLimit&quot;)</value>
      <webElementGuid>84faa08c-bbdc-4ff0-b1f6-9368c881be1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='filterLimit']</value>
      <webElementGuid>3dc59f01-1986-4d36-825f-3cc179f038c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='complex-header-datatable']/div/div/div/div[2]/div/div/div/select</value>
      <webElementGuid>2b03054c-e185-4f71-a47a-98876b6010d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List of Customers'])[1]/following::select[1]</value>
      <webElementGuid>52613cc9-411a-485a-818d-f3a1b6a57db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Management'])[2]/following::select[1]</value>
      <webElementGuid>341c018b-4f09-4962-8cee-b6456ca66736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[1]/preceding::select[2]</value>
      <webElementGuid>9c2011f9-7758-4615-b368-86c20d3afdbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>d683a296-79dc-4a0a-a8ee-db5b38af4f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'filterLimit' and @id = 'filterLimit' and (text() = '
                                                Show
                                                5
                                                10
                                                25
                                                50
                                                100
                                                500
                                                1000
                                            ' or . = '
                                                Show
                                                5
                                                10
                                                25
                                                50
                                                100
                                                500
                                                1000
                                            ')]</value>
      <webElementGuid>4ecef111-ae9c-434b-8b4c-a4f9f1568117</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
