<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit</name>
   <tag></tag>
   <elementGuidId>d545ccc9-b705-48d4-92b9-979cd61be0b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-flat-info.btn-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tbl-wording-notif']/tbody/tr/td[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>96930560-a49e-4bad-941f-977a474caebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat-dashboard.blicicil.com/config/wording/edit?token=61e82262c07d950ff471e822</value>
      <webElementGuid>37014ce0-6f91-454d-98c4-5b98f7187647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-flat-info btn-sm</value>
      <webElementGuid>939532ce-a72d-49aa-a360-14d69e82d245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>765ba188-f3cc-4305-b911-7c399f0b5aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl-wording-notif&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[3]/a[@class=&quot;btn btn-flat-info btn-sm&quot;]</value>
      <webElementGuid>3f8fe4ad-e572-4428-ba31-e3ad348d1acd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbl-wording-notif']/tbody/tr/td[3]/a</value>
      <webElementGuid>e683ccf4-67b7-42e9-a8ae-89176481f3ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Edit')]</value>
      <webElementGuid>cfdb299e-f16a-4de5-bddf-4f7ed3144bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fasilitas Belum Tersedia'])[1]/following::a[1]</value>
      <webElementGuid>244bc04b-f201-4461-8eff-c1ef8ffea14d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::a[1]</value>
      <webElementGuid>2f627cbf-1864-48aa-a13b-e662908bb3cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Domisili Tidak Dicover'])[1]/preceding::a[1]</value>
      <webElementGuid>eb7ddd73-549a-4728-9096-aea2e22cea83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat domisili Anda terlalu jauh dengan alamat KTP, Proses tidak dapat dilanjutkan.'])[1]/preceding::a[1]</value>
      <webElementGuid>8d247892-e62d-49c0-ae1e-14dfb2f8d42f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>8b15996a-3586-4c47-aacd-f4bab301bb1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://uat-dashboard.blicicil.com/config/wording/edit?token=61e82262c07d950ff471e822')]</value>
      <webElementGuid>b9f20726-fa8c-4c69-91f4-49d56c4a24df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>3278e529-2183-4521-ae52-ca5dcafe8dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat-dashboard.blicicil.com/config/wording/edit?token=61e82262c07d950ff471e822' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>1bdde88c-91ae-4d42-a89b-517f7064c260</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
