<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Aceh SelatanBalanganBalikpapanBantae_4910c5</name>
   <tag></tag>
   <elementGuidId>a3029b1d-f018-4602-a242-30cc484d83c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#comboBoxKota</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='comboBoxKota']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>032ebd61-ff48-4492-8f5c-d60319158a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control</value>
      <webElementGuid>44c88a38-2df5-4a71-b02d-ea05254aff68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comboBoxKota</value>
      <webElementGuid>b8c723a9-4e4d-4a76-ae55-b1729a323107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>comboBoxKota</value>
      <webElementGuid>dd32cee3-c5b6-47c3-ac02-5377d483baf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aceh SelatanBalanganBalikpapanBantaengBekasi KotaAceh SingkilAceh UtaraBandung KotaBanggaiBarito SelatanBengkulu TengahAceh BaratAceh JayaAceh TimurBadungBandung BaratBangliBanyuasinBarruBatamBekasiBeluBandar LampungBandungBanggai KepulauanBangka TengahBantulBarito TimurBatu BaraBengkayangAceh BesarAceh TamiangAceh TengahAceh TenggaraAmbonAsmatBanjarbaruBanyuwangiBarito UtaraBatangBau-BauBengkalisAceh Barat DayaBangkaBanjarnegaraBanyumasBatang HariBelitung TimurBener MeriahBengkuluBengkulu SelatanAlorAsahanBanda AcehBangka BaratBangka SelatanBangkalanBatuBelitungAgamBanjarBanjar KotaBanjarmasinBarito KualaBlitarBima KotaBlitar KotaBloraBogor KotaBolaang Mongondow TimurBoneBoyolaliBulelengButon UtaraGarutGorontalo UtaraGowaGunungsitoliIndramayuJakarta SelatanJayawijayaJembranaKarawangKatinganKayong UtaraKeeromKendalKepulauan MentawaiKepulauan SeribuKolakaKolaka TimurKolaka UtaraKuantan SingingiKudusLahatLebakMagetanMahakam UluMamuju TengahMedanMelawiMetroNabireNagan RayaNagekeoNgawiNunukanOgan IlirOgan Komering IlirPadang PanjangPaniaiPegunungan BintangPematang SiantarPidie JayaPurworejoRejang LebongSamosirSelayar (Kepulauan Selayar)SemarangSeram Bagian BaratSijunjungSintangSolokSolok KotaSoppengBoven DigoelCiamisCirebonCirebon KotaFlores TimurGorontalo KotaHalmahera SelatanIntan JayaJakarta BaratKABUPATEN MINAHASAKaimanaKarimunKediri KotaKepulauan AruKotawaringin BaratLampung SelatanLampung UtaraLumajangMadiunMagelangMakassarManadoManggarai TimurMorowali UtaraNdugaNgadaPadangPakpak BharatPalembangPamekasanPASANGKAYUPasangkayu (Mamuju Utara)PaserPenajam Paser UtaraPohuwatoSabu RaijuaSalatigaSerangSerang KotaSiakBitungBrebesBungoDeli SerdangDemakDompuEmpat LawangGayo LuesGianyarHalmahera BaratHalmahera TengahJakarta PusatJakarta TimurJakarta UtaraKabupaten Kepulauan TanimbarKendariKerinciKlatenKlungkungKOTA PANGKAL PINANGkota tomohonKotawaringin TimurLanny JayaLembataLima Puluh Koto/KotaLuwu TimurMalinauManggarai BaratMappiMarosMataramMinahasa SelatanMuara EnimMurung RayaMUSI RAWAS UTARANganjukNias UtaraPalangka RayaPangkal PinangPareparePesisir SelatanPonorogoPontianakPontianak KotaPrabumulihProbolinggoRote NdaoSeram Bagian TimurSolok SelatanSorong KotaBogorBolaang Mongondow (Bolmong)Bolaang Mongondow (Bolmong) UtaraBone BolangoBuruCimahiDairiDharmasrayaHalmahera UtaraJombangKapuas HuluKarangasemKaroKebumenKepahiangKonawe SelatanKotabaruKulon ProgoKupang KotaKutai BaratKutai KartanegaraLabuhan Batu SelatanLamonganLampung BaratLangkatLangsaLombok BaratLombok TengahLombok TimurMagelang KotaMalang KotaMamasaMamberamo RayaMaybratMempawahMeraukeMojokertoNatunaOgan Komering Ulu SelatanOgan Komering Ulu TimurPadang Lawas UtaraPadang SidempuanPandeglangPasuruan KotaPatiPringsewuProbolinggo KotaPuncakPuncak JayaRokan HuluSelumaSemarang KotaSerdang BedagaiSibolgaSidenreng Rappang/RapangSidoarjoSijunjung (Sawah Lunto Sijunjung)BimaBulukumbaBondowosoBontangDonggalaEndeIndragiri HilirJayapura KotaJemberJeparaKABUPATEN BANJARKABUPATEN MINAHASA TENGGARAKediriKepulauan AnambasKepulauan Siau Tagulandang Biaro (Sitaro)KetapangKOTA BANJARMASINLampung TimurLebongLuwuMadiun KotaMajalengkaMaluku TenggaraMamberamo TengahManggaraiMinahasaMinahasa TenggaraMorowaliMusi Rawas UtaraNias BaratNias SelatanPacitanPalopoPelalawanPemalangPidiePolewali MandarRokan HilirSawah LuntoSeruyanSigiSikkaBulungan (Bulongan)BuolButonDumaiGorontaloGroboganGunung Kidulkabupaten PasuruanKamparKapuasKaranganyarKepulauan MerantiKepulauan SangiheKepulauan TalaudKonaweKonawe UtaraKota ProbolinggoKupangLabuhan Batu UtaraLampung TengahLandakLhokseumaweLinggaLubuk LinggauMajeneMalangMaluku TengahMaluku Tenggara BaratMamujuMimikaNiasPadang LawasPagar AlamPangandaranPangkajene KepulauanPariamanPasaman BaratPasuruanPekalongan KotaPekanbaruRaja AmpatRembangSabangSamarindaSambasSampangSarmiSekadauSimalungunSimeulueSinjaiBengkulu UtaraBiak NumforBintanBireuenBoalemoCianjurDenpasarDepokEnrekangFakfakGresikGunung MasHalmahera TimurHumbang HasundutanIndragiri HuluJenepontoKabupaten Oku TimurKepulauan Yapen (Yapen Waropen)KotamobaguKuninganKupang KotaLamandauMaluku Barat DayaManokwariMesujiMinahasa UtaraMojokerto KotaMuko MukoMunaOgan Komering UluPadang PariamanParigi MoutongPenukal Abab Lematang IlirPinrangPulang PisauPurbalinggaSarolangunBerauBinjaiBojonegoroBolaang Mongondow SelatanBolaang Mongondow UtaraBombanaBukittinggiBuru SelatanCilacapCilegonDeiyai (Deliyai)DogiyaiHulu Sungai SelatanHulu Sungai TengahHulu Sungai UtaraJambiJayapuraKaurKepulauan SulaKOTA GORONTALOKubu RayaKutai TimurLabuhan BatuLombok UtaraLuwu UtaraMalakaMandailing NatalMeranginMuaro JambiMusi BanyuasinMusi RawasPaluPasamanPayakumbuhPekalonganPesawaranPesisir BaratPosoPulau MorotaiPurwakartaSanggauSingkawangSitubondoSlemanSorongSorong SelatanSumba BaratSragenSumedangTanah LautTangerang KotaTangerang SelatanTulang BawangTulungagungWaropenTabalongTana TidungTanjung BalaiTapanuli TengahTernateTojo Una-UnaToli-ToliTomohonTualWay KananSumenepTabananTasikmalayaTasikmalaya KotaTeboTemanggungToraja UtaraWonogiriYogyakartaSukabumi KotaSubangSubulussalamSukamaraTambrauwTanjung Jabung BaratTegalTimor Tengah SelatanYalimoSumbawaSumbawa BaratSupioriSurakarta (Solo)TangerangTanjung Jabung TimurTanjung PinangWajoSukabumiSukoharjoSurabayaTanah DatarTapanuli UtaraTarakanTeluk BintuniTolikaraTrenggalekTulang Bawang BaratWakatobiSumba Barat DayaSumba TengahSumba TimurTanah BumbuTanggamusTapanuli SelatanTegal KotaTeluk WondamaTidore KepulauanTimor Tengah UtaraTubanWonosoboSungaipenuhTakalarTana TorajaTapinTebing TinggiToba SamosirYahukimo</value>
      <webElementGuid>bd4b99b3-7b20-4b1a-bf37-f1b8bd1e5327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comboBoxKota&quot;)</value>
      <webElementGuid>8563df51-befe-460f-a32d-a9f8bc72401f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='comboBoxKota']</value>
      <webElementGuid>ed16f955-221b-44cb-a237-533f2e9eff66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmToko']/div[2]/div/div/select</value>
      <webElementGuid>51cca7bd-4834-40c3-9aec-db61756d14e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/following::select[1]</value>
      <webElementGuid>0cef9059-1d40-4d34-bcd3-bdd13cb22e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merchant'])[1]/following::select[2]</value>
      <webElementGuid>2b5363d0-4841-42da-a6a1-0c0f246a56dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Toko'])[1]/preceding::select[1]</value>
      <webElementGuid>d53a6bc7-5bbf-4f08-828b-4d586f9277cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outlet Name'])[1]/preceding::select[1]</value>
      <webElementGuid>583e76aa-e970-4e79-8125-ad2505fb783c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>9195ea2f-ea42-4636-8b74-dddce5ff102e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'comboBoxKota' and @name = 'comboBoxKota' and (text() = 'Aceh SelatanBalanganBalikpapanBantaengBekasi KotaAceh SingkilAceh UtaraBandung KotaBanggaiBarito SelatanBengkulu TengahAceh BaratAceh JayaAceh TimurBadungBandung BaratBangliBanyuasinBarruBatamBekasiBeluBandar LampungBandungBanggai KepulauanBangka TengahBantulBarito TimurBatu BaraBengkayangAceh BesarAceh TamiangAceh TengahAceh TenggaraAmbonAsmatBanjarbaruBanyuwangiBarito UtaraBatangBau-BauBengkalisAceh Barat DayaBangkaBanjarnegaraBanyumasBatang HariBelitung TimurBener MeriahBengkuluBengkulu SelatanAlorAsahanBanda AcehBangka BaratBangka SelatanBangkalanBatuBelitungAgamBanjarBanjar KotaBanjarmasinBarito KualaBlitarBima KotaBlitar KotaBloraBogor KotaBolaang Mongondow TimurBoneBoyolaliBulelengButon UtaraGarutGorontalo UtaraGowaGunungsitoliIndramayuJakarta SelatanJayawijayaJembranaKarawangKatinganKayong UtaraKeeromKendalKepulauan MentawaiKepulauan SeribuKolakaKolaka TimurKolaka UtaraKuantan SingingiKudusLahatLebakMagetanMahakam UluMamuju TengahMedanMelawiMetroNabireNagan RayaNagekeoNgawiNunukanOgan IlirOgan Komering IlirPadang PanjangPaniaiPegunungan BintangPematang SiantarPidie JayaPurworejoRejang LebongSamosirSelayar (Kepulauan Selayar)SemarangSeram Bagian BaratSijunjungSintangSolokSolok KotaSoppengBoven DigoelCiamisCirebonCirebon KotaFlores TimurGorontalo KotaHalmahera SelatanIntan JayaJakarta BaratKABUPATEN MINAHASAKaimanaKarimunKediri KotaKepulauan AruKotawaringin BaratLampung SelatanLampung UtaraLumajangMadiunMagelangMakassarManadoManggarai TimurMorowali UtaraNdugaNgadaPadangPakpak BharatPalembangPamekasanPASANGKAYUPasangkayu (Mamuju Utara)PaserPenajam Paser UtaraPohuwatoSabu RaijuaSalatigaSerangSerang KotaSiakBitungBrebesBungoDeli SerdangDemakDompuEmpat LawangGayo LuesGianyarHalmahera BaratHalmahera TengahJakarta PusatJakarta TimurJakarta UtaraKabupaten Kepulauan TanimbarKendariKerinciKlatenKlungkungKOTA PANGKAL PINANGkota tomohonKotawaringin TimurLanny JayaLembataLima Puluh Koto/KotaLuwu TimurMalinauManggarai BaratMappiMarosMataramMinahasa SelatanMuara EnimMurung RayaMUSI RAWAS UTARANganjukNias UtaraPalangka RayaPangkal PinangPareparePesisir SelatanPonorogoPontianakPontianak KotaPrabumulihProbolinggoRote NdaoSeram Bagian TimurSolok SelatanSorong KotaBogorBolaang Mongondow (Bolmong)Bolaang Mongondow (Bolmong) UtaraBone BolangoBuruCimahiDairiDharmasrayaHalmahera UtaraJombangKapuas HuluKarangasemKaroKebumenKepahiangKonawe SelatanKotabaruKulon ProgoKupang KotaKutai BaratKutai KartanegaraLabuhan Batu SelatanLamonganLampung BaratLangkatLangsaLombok BaratLombok TengahLombok TimurMagelang KotaMalang KotaMamasaMamberamo RayaMaybratMempawahMeraukeMojokertoNatunaOgan Komering Ulu SelatanOgan Komering Ulu TimurPadang Lawas UtaraPadang SidempuanPandeglangPasuruan KotaPatiPringsewuProbolinggo KotaPuncakPuncak JayaRokan HuluSelumaSemarang KotaSerdang BedagaiSibolgaSidenreng Rappang/RapangSidoarjoSijunjung (Sawah Lunto Sijunjung)BimaBulukumbaBondowosoBontangDonggalaEndeIndragiri HilirJayapura KotaJemberJeparaKABUPATEN BANJARKABUPATEN MINAHASA TENGGARAKediriKepulauan AnambasKepulauan Siau Tagulandang Biaro (Sitaro)KetapangKOTA BANJARMASINLampung TimurLebongLuwuMadiun KotaMajalengkaMaluku TenggaraMamberamo TengahManggaraiMinahasaMinahasa TenggaraMorowaliMusi Rawas UtaraNias BaratNias SelatanPacitanPalopoPelalawanPemalangPidiePolewali MandarRokan HilirSawah LuntoSeruyanSigiSikkaBulungan (Bulongan)BuolButonDumaiGorontaloGroboganGunung Kidulkabupaten PasuruanKamparKapuasKaranganyarKepulauan MerantiKepulauan SangiheKepulauan TalaudKonaweKonawe UtaraKota ProbolinggoKupangLabuhan Batu UtaraLampung TengahLandakLhokseumaweLinggaLubuk LinggauMajeneMalangMaluku TengahMaluku Tenggara BaratMamujuMimikaNiasPadang LawasPagar AlamPangandaranPangkajene KepulauanPariamanPasaman BaratPasuruanPekalongan KotaPekanbaruRaja AmpatRembangSabangSamarindaSambasSampangSarmiSekadauSimalungunSimeulueSinjaiBengkulu UtaraBiak NumforBintanBireuenBoalemoCianjurDenpasarDepokEnrekangFakfakGresikGunung MasHalmahera TimurHumbang HasundutanIndragiri HuluJenepontoKabupaten Oku TimurKepulauan Yapen (Yapen Waropen)KotamobaguKuninganKupang KotaLamandauMaluku Barat DayaManokwariMesujiMinahasa UtaraMojokerto KotaMuko MukoMunaOgan Komering UluPadang PariamanParigi MoutongPenukal Abab Lematang IlirPinrangPulang PisauPurbalinggaSarolangunBerauBinjaiBojonegoroBolaang Mongondow SelatanBolaang Mongondow UtaraBombanaBukittinggiBuru SelatanCilacapCilegonDeiyai (Deliyai)DogiyaiHulu Sungai SelatanHulu Sungai TengahHulu Sungai UtaraJambiJayapuraKaurKepulauan SulaKOTA GORONTALOKubu RayaKutai TimurLabuhan BatuLombok UtaraLuwu UtaraMalakaMandailing NatalMeranginMuaro JambiMusi BanyuasinMusi RawasPaluPasamanPayakumbuhPekalonganPesawaranPesisir BaratPosoPulau MorotaiPurwakartaSanggauSingkawangSitubondoSlemanSorongSorong SelatanSumba BaratSragenSumedangTanah LautTangerang KotaTangerang SelatanTulang BawangTulungagungWaropenTabalongTana TidungTanjung BalaiTapanuli TengahTernateTojo Una-UnaToli-ToliTomohonTualWay KananSumenepTabananTasikmalayaTasikmalaya KotaTeboTemanggungToraja UtaraWonogiriYogyakartaSukabumi KotaSubangSubulussalamSukamaraTambrauwTanjung Jabung BaratTegalTimor Tengah SelatanYalimoSumbawaSumbawa BaratSupioriSurakarta (Solo)TangerangTanjung Jabung TimurTanjung PinangWajoSukabumiSukoharjoSurabayaTanah DatarTapanuli UtaraTarakanTeluk BintuniTolikaraTrenggalekTulang Bawang BaratWakatobiSumba Barat DayaSumba TengahSumba TimurTanah BumbuTanggamusTapanuli SelatanTegal KotaTeluk WondamaTidore KepulauanTimor Tengah UtaraTubanWonosoboSungaipenuhTakalarTana TorajaTapinTebing TinggiToba SamosirYahukimo' or . = 'Aceh SelatanBalanganBalikpapanBantaengBekasi KotaAceh SingkilAceh UtaraBandung KotaBanggaiBarito SelatanBengkulu TengahAceh BaratAceh JayaAceh TimurBadungBandung BaratBangliBanyuasinBarruBatamBekasiBeluBandar LampungBandungBanggai KepulauanBangka TengahBantulBarito TimurBatu BaraBengkayangAceh BesarAceh TamiangAceh TengahAceh TenggaraAmbonAsmatBanjarbaruBanyuwangiBarito UtaraBatangBau-BauBengkalisAceh Barat DayaBangkaBanjarnegaraBanyumasBatang HariBelitung TimurBener MeriahBengkuluBengkulu SelatanAlorAsahanBanda AcehBangka BaratBangka SelatanBangkalanBatuBelitungAgamBanjarBanjar KotaBanjarmasinBarito KualaBlitarBima KotaBlitar KotaBloraBogor KotaBolaang Mongondow TimurBoneBoyolaliBulelengButon UtaraGarutGorontalo UtaraGowaGunungsitoliIndramayuJakarta SelatanJayawijayaJembranaKarawangKatinganKayong UtaraKeeromKendalKepulauan MentawaiKepulauan SeribuKolakaKolaka TimurKolaka UtaraKuantan SingingiKudusLahatLebakMagetanMahakam UluMamuju TengahMedanMelawiMetroNabireNagan RayaNagekeoNgawiNunukanOgan IlirOgan Komering IlirPadang PanjangPaniaiPegunungan BintangPematang SiantarPidie JayaPurworejoRejang LebongSamosirSelayar (Kepulauan Selayar)SemarangSeram Bagian BaratSijunjungSintangSolokSolok KotaSoppengBoven DigoelCiamisCirebonCirebon KotaFlores TimurGorontalo KotaHalmahera SelatanIntan JayaJakarta BaratKABUPATEN MINAHASAKaimanaKarimunKediri KotaKepulauan AruKotawaringin BaratLampung SelatanLampung UtaraLumajangMadiunMagelangMakassarManadoManggarai TimurMorowali UtaraNdugaNgadaPadangPakpak BharatPalembangPamekasanPASANGKAYUPasangkayu (Mamuju Utara)PaserPenajam Paser UtaraPohuwatoSabu RaijuaSalatigaSerangSerang KotaSiakBitungBrebesBungoDeli SerdangDemakDompuEmpat LawangGayo LuesGianyarHalmahera BaratHalmahera TengahJakarta PusatJakarta TimurJakarta UtaraKabupaten Kepulauan TanimbarKendariKerinciKlatenKlungkungKOTA PANGKAL PINANGkota tomohonKotawaringin TimurLanny JayaLembataLima Puluh Koto/KotaLuwu TimurMalinauManggarai BaratMappiMarosMataramMinahasa SelatanMuara EnimMurung RayaMUSI RAWAS UTARANganjukNias UtaraPalangka RayaPangkal PinangPareparePesisir SelatanPonorogoPontianakPontianak KotaPrabumulihProbolinggoRote NdaoSeram Bagian TimurSolok SelatanSorong KotaBogorBolaang Mongondow (Bolmong)Bolaang Mongondow (Bolmong) UtaraBone BolangoBuruCimahiDairiDharmasrayaHalmahera UtaraJombangKapuas HuluKarangasemKaroKebumenKepahiangKonawe SelatanKotabaruKulon ProgoKupang KotaKutai BaratKutai KartanegaraLabuhan Batu SelatanLamonganLampung BaratLangkatLangsaLombok BaratLombok TengahLombok TimurMagelang KotaMalang KotaMamasaMamberamo RayaMaybratMempawahMeraukeMojokertoNatunaOgan Komering Ulu SelatanOgan Komering Ulu TimurPadang Lawas UtaraPadang SidempuanPandeglangPasuruan KotaPatiPringsewuProbolinggo KotaPuncakPuncak JayaRokan HuluSelumaSemarang KotaSerdang BedagaiSibolgaSidenreng Rappang/RapangSidoarjoSijunjung (Sawah Lunto Sijunjung)BimaBulukumbaBondowosoBontangDonggalaEndeIndragiri HilirJayapura KotaJemberJeparaKABUPATEN BANJARKABUPATEN MINAHASA TENGGARAKediriKepulauan AnambasKepulauan Siau Tagulandang Biaro (Sitaro)KetapangKOTA BANJARMASINLampung TimurLebongLuwuMadiun KotaMajalengkaMaluku TenggaraMamberamo TengahManggaraiMinahasaMinahasa TenggaraMorowaliMusi Rawas UtaraNias BaratNias SelatanPacitanPalopoPelalawanPemalangPidiePolewali MandarRokan HilirSawah LuntoSeruyanSigiSikkaBulungan (Bulongan)BuolButonDumaiGorontaloGroboganGunung Kidulkabupaten PasuruanKamparKapuasKaranganyarKepulauan MerantiKepulauan SangiheKepulauan TalaudKonaweKonawe UtaraKota ProbolinggoKupangLabuhan Batu UtaraLampung TengahLandakLhokseumaweLinggaLubuk LinggauMajeneMalangMaluku TengahMaluku Tenggara BaratMamujuMimikaNiasPadang LawasPagar AlamPangandaranPangkajene KepulauanPariamanPasaman BaratPasuruanPekalongan KotaPekanbaruRaja AmpatRembangSabangSamarindaSambasSampangSarmiSekadauSimalungunSimeulueSinjaiBengkulu UtaraBiak NumforBintanBireuenBoalemoCianjurDenpasarDepokEnrekangFakfakGresikGunung MasHalmahera TimurHumbang HasundutanIndragiri HuluJenepontoKabupaten Oku TimurKepulauan Yapen (Yapen Waropen)KotamobaguKuninganKupang KotaLamandauMaluku Barat DayaManokwariMesujiMinahasa UtaraMojokerto KotaMuko MukoMunaOgan Komering UluPadang PariamanParigi MoutongPenukal Abab Lematang IlirPinrangPulang PisauPurbalinggaSarolangunBerauBinjaiBojonegoroBolaang Mongondow SelatanBolaang Mongondow UtaraBombanaBukittinggiBuru SelatanCilacapCilegonDeiyai (Deliyai)DogiyaiHulu Sungai SelatanHulu Sungai TengahHulu Sungai UtaraJambiJayapuraKaurKepulauan SulaKOTA GORONTALOKubu RayaKutai TimurLabuhan BatuLombok UtaraLuwu UtaraMalakaMandailing NatalMeranginMuaro JambiMusi BanyuasinMusi RawasPaluPasamanPayakumbuhPekalonganPesawaranPesisir BaratPosoPulau MorotaiPurwakartaSanggauSingkawangSitubondoSlemanSorongSorong SelatanSumba BaratSragenSumedangTanah LautTangerang KotaTangerang SelatanTulang BawangTulungagungWaropenTabalongTana TidungTanjung BalaiTapanuli TengahTernateTojo Una-UnaToli-ToliTomohonTualWay KananSumenepTabananTasikmalayaTasikmalaya KotaTeboTemanggungToraja UtaraWonogiriYogyakartaSukabumi KotaSubangSubulussalamSukamaraTambrauwTanjung Jabung BaratTegalTimor Tengah SelatanYalimoSumbawaSumbawa BaratSupioriSurakarta (Solo)TangerangTanjung Jabung TimurTanjung PinangWajoSukabumiSukoharjoSurabayaTanah DatarTapanuli UtaraTarakanTeluk BintuniTolikaraTrenggalekTulang Bawang BaratWakatobiSumba Barat DayaSumba TengahSumba TimurTanah BumbuTanggamusTapanuli SelatanTegal KotaTeluk WondamaTidore KepulauanTimor Tengah UtaraTubanWonosoboSungaipenuhTakalarTana TorajaTapinTebing TinggiToba SamosirYahukimo')]</value>
      <webElementGuid>1b009b86-431b-430c-8655-c5921f731845</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
