<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Location_txtLocation</name>
   <tag></tag>
   <elementGuidId>0ae2fddd-a9a4-47b8-954a-fe500506650a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtLocation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtLocation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65fa0016-60c7-4c14-99bc-5d089f31b492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fcae8d4c-cae2-49da-ad95-cb76edc0a0b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtLocation</value>
      <webElementGuid>82ec24a6-2a1c-47cc-b0ca-a3a2f0cd2d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>33ca7b6a-842a-437c-ba2a-1d3f86b8945c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan lokasi notifikasi</value>
      <webElementGuid>9d1e26f6-4af8-4727-954c-51f0f95894f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtLocation</value>
      <webElementGuid>b9a9c345-ee05-47d3-8130-50814f19e79e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtLocation&quot;)</value>
      <webElementGuid>644ed32f-d781-40bc-8cd9-87652e76a0f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtLocation']</value>
      <webElementGuid>26ee7139-3500-41ff-a46e-6b27202492aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmProduct']/div[3]/div/div/input</value>
      <webElementGuid>a5b0dcc6-0e51-4255-b6e5-f82cd80f1024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>5973f949-7661-4712-b78b-ef7d847b805b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtLocation' and @placeholder = 'Masukkan lokasi notifikasi' and @name = 'txtLocation']</value>
      <webElementGuid>a6950ccd-d7ef-4c0e-982e-750510b20c82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
