<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Title_txtTitle</name>
   <tag></tag>
   <elementGuidId>07852298-1ef3-4831-a850-b6600e6f4269</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5214703b-da71-4180-a8eb-f1d6fa5610e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fcf85fc5-6d4e-4e3e-9b56-05b050a89155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtTitle</value>
      <webElementGuid>01775333-5ec6-42ef-b037-7813422c381e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4465b360-62ac-4070-9e26-faae83db49ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan judul notifikasi</value>
      <webElementGuid>bf4f4582-58f9-42e4-95d3-d013ee86d9da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtTitle</value>
      <webElementGuid>68557764-2222-47b8-8d09-773f8cc7af58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtTitle&quot;)</value>
      <webElementGuid>ac71376f-aa9a-4cde-bb78-23b759febc67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtTitle']</value>
      <webElementGuid>3ebc97b6-d67a-478c-8e4a-e965b7bedbc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmProduct']/div/div/div/input</value>
      <webElementGuid>85b5c457-26b2-422c-8f87-8fc6902ea19d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>90bad20e-ed55-459a-8224-02b7a9b895c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtTitle' and @placeholder = 'Masukkan judul notifikasi' and @name = 'txtTitle']</value>
      <webElementGuid>8135bbd2-ae81-4f6f-bbc4-0fbaf093a06f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
