<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Desc_txtDesc</name>
   <tag></tag>
   <elementGuidId>4152e3c5-6354-4d00-a8cc-ae3d72240fd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtDesc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtDesc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c55cb3ea-3260-456e-a864-2e303eea35d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDesc</value>
      <webElementGuid>c46236ca-45e2-46ca-ad06-fcd3bdaeb007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>90f3cdd0-0a06-40fa-a772-2f76ccd5bca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan deskripsi notifikasi</value>
      <webElementGuid>dfd835f4-e08c-4d98-887c-7bf3e0c73a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDesc</value>
      <webElementGuid>7774fa62-2c1a-4147-aec9-8106e821f716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDesc&quot;)</value>
      <webElementGuid>e3eec327-a97a-4e02-9b84-6228400a09ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txtDesc']</value>
      <webElementGuid>8e57d014-b2ed-4509-910b-7788f8881fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmProduct']/div[2]/div/div/textarea</value>
      <webElementGuid>8325aedf-a0f2-414c-b212-a6853f66240e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>f45a8cbe-56b1-4f5f-8bd7-9ff2ef786dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'txtDesc' and @placeholder = 'Masukkan deskripsi notifikasi' and @name = 'txtDesc']</value>
      <webElementGuid>26f83b22-27f7-43ee-b25a-420d727a5ce3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
