<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_E</name>
   <tag></tag>
   <elementGuidId>d4baa05c-1583-4493-bbb1-b3b0a4f4f410</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.avatar-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='dropdown-user']/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b3505533-e970-4874-b411-85aab24d0484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>avatar-content</value>
      <webElementGuid>ae4e667f-9177-422a-9b4a-838b78458193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>E</value>
      <webElementGuid>39c15679-f60d-45cc-9390-c691151f1aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdown-user&quot;)/div[@class=&quot;avatar bg-primary&quot;]/div[@class=&quot;avatar-content&quot;]</value>
      <webElementGuid>1b9841fc-b62a-4f88-ad7d-b951ac32b22b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='dropdown-user']/div[2]/div</value>
      <webElementGuid>e5f5d841-b083-496c-a52a-cfc019bf2531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administrator'])[1]/following::div[2]</value>
      <webElementGuid>f8411c90-d546-4eec-b564-6b095d48129e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eva'])[1]/following::div[2]</value>
      <webElementGuid>0f289c64-971f-47e7-a1a7-722cebfa251a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blicicil'])[1]/preceding::div[2]</value>
      <webElementGuid>27a270c8-fc1f-40aa-863a-6f99659a9153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='E']/parent::*</value>
      <webElementGuid>c2d29718-e6b4-48a6-a276-03c673627695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]/div</value>
      <webElementGuid>c792a2b7-f68d-4396-b681-7123ca75023c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'E' or . = 'E')]</value>
      <webElementGuid>94e5c9a5-ed74-4318-8c63-77cd3a93fd8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
