<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Judul_txtProductName</name>
   <tag></tag>
   <elementGuidId>cee8d623-9c03-43de-8075-800652676bef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtProductName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtProductName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>47643deb-c2ef-4581-8db4-3f5ace76190e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec2d49b6-354d-4e17-846c-5ef8e18f2337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtProductName</value>
      <webElementGuid>e9917df4-2944-4d18-8af1-77608bb414cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6c215e5d-e53c-4bc7-9bd3-227514e6ff1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtProductName</value>
      <webElementGuid>ed463826-d89a-4bfb-879f-db1feaeacda4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Testing hari kamis</value>
      <webElementGuid>a8f35467-45bb-4320-a5a4-b57602b7ae2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Title FAQs</value>
      <webElementGuid>11a65d91-227c-4c01-be23-db8432f868ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtProductName&quot;)</value>
      <webElementGuid>69bde0fa-5d7b-4f8c-8a2f-0dc33362b02b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtProductName']</value>
      <webElementGuid>98638e0d-5523-46f5-b071-98a160d257eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmProduct']/div/div/input</value>
      <webElementGuid>f1e6e330-69e2-449b-bb20-2f7b93a99976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c6266a2a-b78f-41a7-a06d-5e03d58052dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtProductName' and @name = 'txtProductName' and @placeholder = 'Title FAQs']</value>
      <webElementGuid>6ecaae47-8220-4b37-9949-1d6260c7f90f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
