<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Dibatalkan_rotate-icon-620319cf2a632351_42c78f</name>
   <tag></tag>
   <elementGuidId>86d3f623-d85b-4f28-8b81-465be1b62a39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rotate-icon-620319cf2a6323515528da2a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Dibatalkan'])[3]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>55fdcbce-e059-4990-a8ee-ad569b6366d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>76367fba-1818-45f3-9811-a903c8799dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rotate-icon-620319cf2a6323515528da2a</value>
      <webElementGuid>c6dc9ca7-b7c8-4af7-9293-6cd4f8c676ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>toggleIcon('620319cf2a6323515528da2a', false)</value>
      <webElementGuid>dc5e635c-9fdf-4bb4-a176-bd6ef8a90fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>d9416a7b-4fc9-4a11-a3fb-c57c202430bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 12 12</value>
      <webElementGuid>e3bac790-3725-4f01-aa1a-cfabef775dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>2c9110a8-aeae-4569-9853-e79acc893c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>acb0bbea-a93c-4aa4-81a5-04649be0146e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rotate-icon-620319cf2a6323515528da2a&quot;)</value>
      <webElementGuid>5fba3810-c2e1-4b21-b1eb-771c79d266ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dibatalkan'])[3]/following::*[name()='svg'][1]</value>
      <webElementGuid>76ba6af5-d512-44fc-b018-25d29d598b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FMTCC00041'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>845ee42c-0cc0-43a3-b447-ecc5b94f2fad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feb 10 2022 - 11:3AM'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>4aa4baf1-5a3a-42db-bd1d-79a0721f76d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[12]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>e28f7574-8342-4ab5-b988-c4716e461181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//svg[@id = 'rotate-icon-620319cf2a6323515528da2a']</value>
      <webElementGuid>554a5792-bc8a-4fe2-9195-5f88f18100e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
