<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Registration                                                        Date</name>
   <tag></tag>
   <elementGuidId>a35febce-8db8-4abf-8617-d4d6de4ed412</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.text-center.sorting_disabled</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tbl-user-management']/thead/tr/th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>1c42426b-70ea-436f-b876-f224a65d0819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>88352a78-4f6e-4876-b7f8-04f3969f1b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center sorting_disabled</value>
      <webElementGuid>8b7c2c65-b7c8-4cf0-985c-cbc1b3502f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>07f27999-4645-42fa-99bf-dc0176e54ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        Registration
                                                        Date</value>
      <webElementGuid>963eb33f-1cdd-4cf0-8734-dc055ca50ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl-user-management&quot;)/thead[1]/tr[1]/th[@class=&quot;text-center sorting_disabled&quot;]</value>
      <webElementGuid>ef298893-5858-48a8-9d85-76ba4d0d049b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbl-user-management']/thead/tr/th</value>
      <webElementGuid>bcb8525c-aaba-481a-a046-0372577c7806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[1]/following::th[1]</value>
      <webElementGuid>9b5f6753-c0d9-4fcd-8b73-a6a67d8dffd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari:'])[1]/following::th[1]</value>
      <webElementGuid>89750983-c0b0-4345-8bce-04ce96aa6bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::th[1]</value>
      <webElementGuid>5b13c40b-b34d-49cf-99fd-42c5cea351a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[1]/preceding::th[2]</value>
      <webElementGuid>f6f5a5df-cd23-451f-9864-6790879d82e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Registration']/parent::*</value>
      <webElementGuid>a7b24556-ad0e-4a8e-978d-f09d4fc3dcdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th</value>
      <webElementGuid>d2bb8b05-dccd-4515-9fa2-e53d31c13ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = '
                                                        Registration
                                                        Date' or . = '
                                                        Registration
                                                        Date')]</value>
      <webElementGuid>e44edba1-8331-4ac4-870f-cf07d4bce7f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
