<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit</name>
   <tag></tag>
   <elementGuidId>c582cb81-7cf5-4a4d-8811-404bd31a509e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tbl-faq']/tbody/tr[8]/td[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1d7a3134-3a76-4d88-99c4-0e4f60b1e836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat-dashboard.blicicil.com/faqs/edit?token=64546e7f5fb3bc922700c718</value>
      <webElementGuid>df750de8-4385-46bf-8ca0-76f755fa4d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-flat-info</value>
      <webElementGuid>73d55d66-7991-49e1-94eb-cfda4c105f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>801a1e79-2204-4c40-8e1b-2681ffdc7c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl-faq&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[4]/a[@class=&quot;btn btn-flat-info&quot;]</value>
      <webElementGuid>2053b33e-2176-402f-993a-037a89353d85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbl-faq']/tbody/tr[8]/td[4]/a</value>
      <webElementGuid>13ae4a14-ff31-4ea1-b0df-7043b4931806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Edit')])[8]</value>
      <webElementGuid>14bb92eb-62a1-40a7-82c3-8eeba1ce9bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unpublish'])[8]/following::a[1]</value>
      <webElementGuid>2a546d89-d01c-43d3-b3c0-b1d7c9e3064e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publish'])[8]/following::a[1]</value>
      <webElementGuid>6edc074e-0e22-43d0-8564-2b9a45de2e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 21 to 28 of 28 entries'])[1]/preceding::a[1]</value>
      <webElementGuid>a6d61b19-f1ce-4e5c-9e85-e47de8fa16f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://uat-dashboard.blicicil.com/faqs/edit?token=64546e7f5fb3bc922700c718')]</value>
      <webElementGuid>7c10d718-3aec-4ce2-9c57-58c75fb545dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[4]/a</value>
      <webElementGuid>17bdf684-e4dd-4298-9949-bca146fe5ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat-dashboard.blicicil.com/faqs/edit?token=64546e7f5fb3bc922700c718' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>f88250ae-7436-43dd-bdc0-cb7bd31d9f5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
