<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dealer Code_txtDealerCode</name>
   <tag></tag>
   <elementGuidId>3b8d1f48-7d95-4fb2-9430-968e35376b20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtDealerCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtDealerCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>508a216e-038d-46e3-beec-cc6cf9bce86f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>62fa4d3f-7484-43b9-b953-ed3e5d552f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDealerCode</value>
      <webElementGuid>473bfaed-f21e-4a1d-be75-f2d67714a018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input dealer code</value>
      <webElementGuid>a2a3d2d2-0977-4a8c-999c-777cc97d7265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d35f5863-3e51-446f-aff4-2ce9669a5767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDealerCode</value>
      <webElementGuid>85dad4b2-f50c-41e2-b636-89eb5ad98b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDealerCode&quot;)</value>
      <webElementGuid>3c9eaed5-7378-4bed-ba75-76b6aa9b9789</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtDealerCode']</value>
      <webElementGuid>a015852f-a113-4311-9c7b-d9fd6558dbaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmToko']/div[6]/div/div/input</value>
      <webElementGuid>626d2ea1-bf98-4b18-a356-854eb3fd5246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>470f0693-9823-4848-b6eb-569b1e37cac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtDealerCode' and @placeholder = 'Input dealer code' and @name = 'txtDealerCode']</value>
      <webElementGuid>1f9cc9f6-64a9-4210-95b6-5803275a8cea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
