<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Address_txtAlamat</name>
   <tag></tag>
   <elementGuidId>c8b873d4-2515-4274-a0f6-e35aa3b03d67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtAlamat</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtAlamat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b8411081-f5d2-4abd-8c7e-cc20c6c2da0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtAlamat</value>
      <webElementGuid>c53e259e-a987-43b5-83e6-bbb902ba9b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input address</value>
      <webElementGuid>a6d9308e-d739-41ec-adf2-dfaa4072c90c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c57ba2e5-1f16-4f26-af0d-aa392a40304a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtAlamat</value>
      <webElementGuid>1ed89f73-a944-4770-af90-14e2f79b59e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtAlamat&quot;)</value>
      <webElementGuid>2b3ce69a-9cf8-4329-abb1-c1e1783864ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txtAlamat']</value>
      <webElementGuid>2c93f54c-5c2f-498e-95e6-7856c13d5ea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmToko']/div[5]/div/div/textarea</value>
      <webElementGuid>86900d6d-bb40-41da-a841-61fb17445fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>fa373374-0d6e-48e1-beee-7a40fa8e301f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'txtAlamat' and @placeholder = 'Input address' and @name = 'txtAlamat']</value>
      <webElementGuid>7315392b-e55b-4ad5-b0bf-fd99330e3073</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
