<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit</name>
   <tag></tag>
   <elementGuidId>07f3cae7-cee4-4ef1-a45f-7b3721fe4201</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tbl-master-merchants']/tbody/tr/td[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-flat-info</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>07ba202d-9160-4b55-9a8b-aba61d7000fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat-dashboard.blicicil.com/master/merchants/edit?token=633b9bafab41f3ff370f09a1</value>
      <webElementGuid>3a52c48d-6bd2-4438-8f63-689a3e23b75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-flat-info</value>
      <webElementGuid>49abbbbe-b32c-4d4d-aa38-9dd58260e50a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>0f7ba9b9-e35b-43e5-b1db-1f129c9109a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl-master-merchants&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[3]/a[@class=&quot;btn btn-flat-info&quot;]</value>
      <webElementGuid>9712ea04-d07d-4a45-8b09-b7a9f3893fc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbl-master-merchants']/tbody/tr/td[3]/a</value>
      <webElementGuid>c0c5094c-372e-4f4a-af0c-f778dd38248b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Edit')]</value>
      <webElementGuid>6f504ed3-ab21-4c6e-90d0-14763d8d6ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus'])[1]/following::a[1]</value>
      <webElementGuid>d5d50a04-b1c3-499e-a158-784280192b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transmartx'])[1]/following::a[1]</value>
      <webElementGuid>6a1ae251-bb2a-4037-8da0-28509f04d925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Panasonic'])[1]/preceding::a[1]</value>
      <webElementGuid>628a2048-c112-43fe-8aab-caa5fb4d73e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus'])[2]/preceding::a[1]</value>
      <webElementGuid>9234f7a5-f4d6-4a0b-9fc5-e95e3b775a94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>dd372296-8b4e-474f-8dfd-b7ba95e157f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://uat-dashboard.blicicil.com/master/merchants/edit?token=633b9bafab41f3ff370f09a1')]</value>
      <webElementGuid>482d61a0-25cb-403e-a31d-d14529a12f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>b24d8343-b788-4ea5-b1d2-a36601946a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat-dashboard.blicicil.com/master/merchants/edit?token=633b9bafab41f3ff370f09a1' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>8f233b36-5671-4872-9080-d14a7ac71ff5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
