<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kamera Recorder_category</name>
   <tag></tag>
   <elementGuidId>6625e9f6-961b-48f9-b090-a77adfc43e93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='category62f316ad2b878f0347211ea1']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;category62f316ad2b878f0347211ea1&quot;)[count(. | //*[@type = 'checkbox' and @checked = 'true']) = count(//*[@type = 'checkbox' and @checked = 'true'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#category62f316ad2b878f0347211ea1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57941c77-87fe-4e07-b5d2-8ea5de6a3b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1e7a1700-bfe4-4647-b974-ed80abc380ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>05f8fafa-b6d4-4c03-8e83-6c2e5b49fc61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category</value>
      <webElementGuid>f911afa9-84fa-4b1b-abbf-3517aa081b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>fb5fbde1-6634-4150-abcf-0c7184a13fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category62f316ad2b878f0347211ea1</value>
      <webElementGuid>2f2ee635-a2b1-481a-bab3-4a13662da317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>62f316ad2b878f0347211ea1</value>
      <webElementGuid>37867c6a-f016-4d1a-97d8-dcf1f9286c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category62f316ad2b878f0347211ea1&quot;)</value>
      <webElementGuid>e4af2a07-4de9-4ee5-97d7-513836b72223</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='category62f316ad2b878f0347211ea1']</value>
      <webElementGuid>e891a120-dee0-4a40-874d-0cde846bf833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comboBoxCategory']/div[4]/input</value>
      <webElementGuid>0b761354-e0c1-42e1-8a63-d14241308d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>85db0787-16ca-478d-9047-0af42f824043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @checked = 'true' and @name = 'category' and @id = 'category62f316ad2b878f0347211ea1']</value>
      <webElementGuid>70fe8eed-e2df-4890-924f-a9fd38273f0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
