<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pendingin Ruangan_category</name>
   <tag></tag>
   <elementGuidId>9c5ad879-420c-4903-b44a-73f2c4b63578</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#category62f9d04a9ae061df04377ef6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='category62f9d04a9ae061df04377ef6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c58c5981-dae6-470c-97ff-e032099d1d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>30746393-40ca-493f-9129-b65128382c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>4e0cd1ba-4863-4054-899e-c2c3c987bfac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category</value>
      <webElementGuid>a8b5ef44-b67b-4338-abc7-8bd1ebc3d0f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category62f9d04a9ae061df04377ef6</value>
      <webElementGuid>507e0661-7e9d-4e45-9717-ecf6ff3bad4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>62f9d04a9ae061df04377ef6</value>
      <webElementGuid>98a67ef3-ce8c-4b38-924d-9aa0288288d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category62f9d04a9ae061df04377ef6&quot;)</value>
      <webElementGuid>227bb7eb-a817-4d2f-8702-ed15c27a1522</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='category62f9d04a9ae061df04377ef6']</value>
      <webElementGuid>ad4c9bd0-05c3-4505-8bc6-86f5d938cd43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comboBoxCategory']/div[5]/input</value>
      <webElementGuid>29b9889b-8c9a-4854-91f8-3268f0baaed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>078fe1ca-d412-4652-bde2-33e6350f7694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'category' and @id = 'category62f9d04a9ae061df04377ef6']</value>
      <webElementGuid>496136f4-c6a2-4c23-ba12-0b061f9852e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
