<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TV_category</name>
   <tag></tag>
   <elementGuidId>0637efd6-3a86-4d35-98bc-42d9bb5f246b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#category62f3169e2b878f0347211ea0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='category62f3169e2b878f0347211ea0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61afec6d-fa08-449c-abdb-6f3da7771dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8c6ce996-1b91-48ec-9e80-3413db2d3196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2d3512a2-b479-4a45-ba05-5b835022ea24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category</value>
      <webElementGuid>066b8af4-7254-45ee-b3c0-e3b052735592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>fa86d42b-ca1d-4a8d-a2ca-0dd895dd64ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category62f3169e2b878f0347211ea0</value>
      <webElementGuid>f00f3e37-72bd-481e-a921-35f5ff5e74f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>62f3169e2b878f0347211ea0</value>
      <webElementGuid>c0a06b1f-c444-4f04-a018-569b30ac75ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category62f3169e2b878f0347211ea0&quot;)</value>
      <webElementGuid>bec792fc-3bd6-46ca-9047-47580dc3ff1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='category62f3169e2b878f0347211ea0']</value>
      <webElementGuid>5bfa0d40-84d9-4bf9-b177-eeba79a3d942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comboBoxCategory']/div[3]/input</value>
      <webElementGuid>42e09489-9ef4-4d16-8daf-2583f2c3a36a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>82cb0d61-af9d-43c6-b7e2-11d671c1fdac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @checked = 'true' and @name = 'category' and @id = 'category62f3169e2b878f0347211ea0']</value>
      <webElementGuid>c7e68497-e517-4c6a-a0f3-d00cb917507a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
