<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Komputer Laptop_category</name>
   <tag></tag>
   <elementGuidId>a2fc0855-b1dc-404b-affc-f9f1b8206bae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='category62f316842b878f0347211e9e']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;category62f316842b878f0347211e9e&quot;)[count(. | //*[@checked = 'true']) = count(//*[@checked = 'true'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#category62f316842b878f0347211e9e</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e351492f-598a-483c-b8f6-f4d0cbf5b03a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>487629e8-9edb-459c-9fc5-8c7377f95b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>380ba88b-45ce-4e74-8ffc-b18c7bd3a16c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category</value>
      <webElementGuid>57be16dc-3915-46df-8847-3af4252ea4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>69b63963-ffbf-4518-a6e2-9797199115cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category62f316842b878f0347211e9e</value>
      <webElementGuid>459278ea-0e4f-438a-a587-b3fece344782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>62f316842b878f0347211e9e</value>
      <webElementGuid>52951c94-a663-47fd-8885-2aafb06077e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category62f316842b878f0347211e9e&quot;)</value>
      <webElementGuid>3bd9ff73-e436-4aa6-9193-155583960db5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='category62f316842b878f0347211e9e']</value>
      <webElementGuid>38d0119f-21a2-4e28-9c5a-c739830f11fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comboBoxCategory']/div/input</value>
      <webElementGuid>52027fac-8c72-4157-bdcf-863eb3218dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>e4c405ac-7b71-4862-b7a5-33477f184357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @checked = 'true' and @name = 'category' and @id = 'category62f316842b878f0347211e9e']</value>
      <webElementGuid>b63bd417-794e-44c8-b2f0-c6b644fca65a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
