<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Search</name>
   <tag></tag>
   <elementGuidId>f630d719-40fb-48d4-8aa7-44c85d4ecc8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tbl-products_filter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tbl-products_filter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4e9e67c5-b726-4c05-a279-def7503995a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tbl-products_filter</value>
      <webElementGuid>4a331cf5-00d3-4098-8da2-80db18cab629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dataTables_filter</value>
      <webElementGuid>8214ef82-2da2-4ef8-84e9-04f5cc27a36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search:</value>
      <webElementGuid>e022193f-5dd5-4bdb-b6af-9cadadeb6215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl-products_filter&quot;)</value>
      <webElementGuid>007a3b43-3fb0-43d2-8330-b34dc06f539e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tbl-products_filter']</value>
      <webElementGuid>a0a61e0f-dff7-4727-908a-7b31ca41dab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tbl-products_wrapper']/div/div[2]/div</value>
      <webElementGuid>ac7e1d98-d28d-4b98-aab0-2fa918561822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Product'])[1]/following::div[7]</value>
      <webElementGuid>d79c0f71-475a-4091-ae66-5bd07c2040b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List Products BliCicil Admin as'])[1]/following::div[8]</value>
      <webElementGuid>87320d5f-bab1-4c01-999e-bb202f61823c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product'])[1]/preceding::div[1]</value>
      <webElementGuid>e64dc1a8-9817-4290-a4f4-9b8a7dd74ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div</value>
      <webElementGuid>26974e5c-b304-485b-8b2e-da6bcd29137a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tbl-products_filter' and (text() = 'Search:' or . = 'Search:')]</value>
      <webElementGuid>5b06adb6-d44a-42c6-9c9a-5ee469c28dc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
