<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Longitude_txtlongitude</name>
   <tag></tag>
   <elementGuidId>03e7e282-ceaa-4437-b8bb-645031c60ddb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtlongitude</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtlongitude']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd2c6c2e-1925-4315-8e30-74b79fcd40f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4350feb9-01be-4da6-99c5-ff56f5c2453c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\[[+-]?[0-9]*\.?[0-9]+,[+-]?[0-9]*\.?[0-9]+]</value>
      <webElementGuid>838816a3-b127-4fbd-a29f-d70fb150a1c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtlongitude</value>
      <webElementGuid>00955a02-77e5-4bae-85df-27f895599139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2addfed4-1cda-4cce-a147-e1489282c167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtlongitude</value>
      <webElementGuid>480891a4-136f-4144-b369-a34b0139e1c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan longitude</value>
      <webElementGuid>a6b50cc8-35c4-4e2a-bfc5-179d93da6f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return((47&lt;event.keyCode &amp;&amp; event.keyCode&lt;58 &amp;&amp; event.shiftKey==false) || (event.keyCode==190 &amp;&amp; event.shiftKey==false) || event.keyCode==37 || event.keyCode==39 || event.keyCode==46 || event.keyCode==8)</value>
      <webElementGuid>bd2aa1bb-5213-4fe1-9d03-fa6fa4b62aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtlongitude&quot;)</value>
      <webElementGuid>aeeef5bb-aeb1-4091-8645-a4931c2e00fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtlongitude']</value>
      <webElementGuid>f0d8cb3f-eb1d-4168-bd0a-ebd31d94e271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmToko']/div[9]/div/div/input</value>
      <webElementGuid>c0c8dafc-ab2f-41ad-b870-a5a56f2cd890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/input</value>
      <webElementGuid>1daefdda-7966-4c69-a993-e4f0303f88d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtlongitude' and @name = 'txtlongitude' and @placeholder = 'Masukkan longitude']</value>
      <webElementGuid>c257aca6-21d4-435d-8b44-30d1cef0f74c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
