<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Previous</name>
   <tag></tag>
   <elementGuidId>c4ca13c4-f2ed-49a3-a99b-10214a6c06dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='tbl-bank_previous']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.page-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>19dc7f6b-b835-4197-839b-5bc53d569b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>842e1190-d552-4f4b-b910-1c9cb2663cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tbl-bank</value>
      <webElementGuid>0c8b38c4-2c08-413d-ba7c-e8486efc356b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dt-idx</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>24fdc57a-3c12-4b24-b8c6-0cfe7b0d2398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>15819770-7a16-4177-abc4-ae4db79a926f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-link</value>
      <webElementGuid>606cc14f-d87c-4950-a7d2-41a758acf95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Previous</value>
      <webElementGuid>7fd92c68-b6d7-43f2-8ce3-401428f38172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl-bank_previous&quot;)/a[@class=&quot;page-link&quot;]</value>
      <webElementGuid>04695f63-3aaa-4b7b-9e99-7a7ccc6cbbac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tbl-bank_previous']/a</value>
      <webElementGuid>013dbf37-828c-4c57-a8e3-05a8baa49989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Previous')]</value>
      <webElementGuid>bf742358-c481-4fa2-aba7-e4a4a0655f1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 21 to 30 of 59 entries'])[1]/following::a[1]</value>
      <webElementGuid>7d599e89-c3c5-445c-9b20-45105e2bf7a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[10]/following::a[1]</value>
      <webElementGuid>94e2504b-4499-47f2-81da-98d89a5861e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=', All rights Reserved'])[1]/preceding::a[9]</value>
      <webElementGuid>e9e831d4-b440-4add-b7ca-32871c12178d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Previous']/parent::*</value>
      <webElementGuid>df9c1e02-b478-4eff-a090-d8c52a4f8d63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>5c347b05-d6eb-4e5c-92aa-a07bde89b685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/ul/li/a</value>
      <webElementGuid>74e915af-c8a9-43e5-93b7-5b2edfa70874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Previous' or . = 'Previous')]</value>
      <webElementGuid>731b34bf-fac7-40fb-81df-38153e589773</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
